// packages/render-vue/src/components/select/index.tsx
import { observer } from '@/formily-vue';
import { defineComponent } from 'vue';
import { selectProps } from 'ant-design-vue/es/select';
import { Select as AntdSelect } from 'ant-design-vue';

const Select = observer(
  defineComponent({
    name: 'Select',
    inheritAttrs: false,
    props: selectProps(),
    setup(props, { attrs }) {
      return () => {
        const { readOnly } = attrs;
        return readOnly ? <span>{props.value}</span> : <AntdSelect {...props} />;
      };
    },
  }),
);

export default Select

// packages/render/src/components/select/index.tsx
import React, { FC } from 'react';
import { Select as AntdInput, SelectProps } from 'antd';

export const Select: FC<SelectProps & { readOnly: boolean }> = ({
  readOnly,
  value,
  ...restProps
}) => {
  return readOnly ? <span>{value}</span> : <AntdInput value={value} {...restProps} />;
};

export default Select;
