// packages/render/src/scheme-table-form/index.tsx
import { FC, Key, useEffect, useMemo, memo, useState } from 'react';
import { Form, setValidateLanguage } from '@formily/core';
import { FormProvider } from '@formily/react';

import { Empty, Skeleton } from 'antd';

import useCreateSchemaField from '@/hooks/useSchemaField';

import { ISchema } from '@formily/react';
import { toArray } from '@/utils';
import { LIST_FILED_CODE } from '@/utils/constant';
import { ListTableProps } from '@/components/list-table';

import { useDeepEffect, useDOMRect } from '@formlogic/component';
import { RowSelectionType } from 'antd/es/table/interface';
import { Components } from '@/interface';

export interface SchemeTableFormProps
  extends Omit<
    ListTableProps,
    'selectedRowKeys' | 'setSelectedRowKeys' | 'selectedRows' | 'setSelectedRows' | 'onTableChange'
  > {
  schema: ISchema;
  form: Form;
  dataSource: any[];
  currentPage: number;
  total: number;
  pageSize: number;
  language?: string;
  loading?: boolean;
  rowKey?: string;
  hasRowSelection?: boolean;
  hasClearSelectedRows?: boolean;
  selectedRows?: any[];
  rowSelectionType?: RowSelectionType;
  components?: Components;
}

const SchemeTableForm: FC<SchemeTableFormProps> = ({
  schema,
  loading,
  language,
  components,
  dataSource,
  form,
  selectedRows: defaultSelectedRows,
  rowKey,
  hasRowSelection,
  rowSelection,
  onChange,
  currentPage,
  total,
  pageSize,
  rowSelectionType,
  hasClearSelectedRows,
  ...restProps
}) => {
  const [selectedRowKeys, setSelectedRowKeys] = useState<Key[]>([]);

  const [selectedRows, setSelectedRows] = useState<any[]>([]);

  const SchemaField = useCreateSchemaField();

  const [scrollY, setScrollY] = useState(450);

  const [contentRect, domRef] = useDOMRect<HTMLDivElement>();

  const tableRowKey = useMemo(() => {
    return rowKey || 'id';
  }, [rowKey]);

  useEffect(() => {
    if (contentRect) {
      const { height } = contentRect;
      setScrollY(height - 140);
    }
  }, [contentRect]);

  useEffect(() => {
    setValidateLanguage(language ?? 'zh-CN');
  }, [language]);

  useEffect(() => {
    if (form.id) {
      form.setValuesIn(LIST_FILED_CODE, dataSource);

      if (hasClearSelectedRows) {
        setSelectedRows([]);
        setSelectedRowKeys([]);
      }
    }
  }, [form?.id, dataSource, hasClearSelectedRows]);

  useEffect(() => {
    setSelectedRowKeys(defaultSelectedRows?.map((item: any) => item[tableRowKey]) || []);
    setSelectedRows(defaultSelectedRows || []);
  }, [defaultSelectedRows, tableRowKey]);

  const handleRowSelectionChange = (rowKeys: Key[], changeSelectedRows: any[], info) => {
    if (rowSelectionType === 'radio') {
      setSelectedRows(changeSelectedRows);
      setSelectedRowKeys(rowKeys);

      rowSelection?.onChange?.(rowKeys, changeSelectedRows, info);
    } else {
      const allDataSourceKey =
        toArray(dataSource).map((item: any, index) => item[tableRowKey] || index) || [];

      // 更新旧值选中的数据
      const selectedRowsMap = toArray(defaultSelectedRows).map((item: any) => {
        const record = changeSelectedRows.find(
          (current) => current[tableRowKey] === item[tableRowKey],
        );
        if (record) {
          return record;
        }
        return item;
      });

      const nextSelectedRows = selectedRowsMap
        .filter((item: any) => !allDataSourceKey.includes(item[tableRowKey]))
        .concat(changeSelectedRows.filter((item) => allDataSourceKey.includes(item[tableRowKey])));

      const nextSelectedRowKeys = nextSelectedRows.map((item: any) => item[tableRowKey]);

      setSelectedRows(nextSelectedRows);

      setSelectedRowKeys(nextSelectedRowKeys);

      rowSelection?.onChange?.(nextSelectedRowKeys, nextSelectedRows, info);
    }
  };

  const getRowSelectionConfig = () => {
    if (hasRowSelection) {
      return {
        ...rowSelection,
        selectedRowKeys,
        selectedRows,
        type: rowSelectionType ?? 'checkbox',
        onChange: handleRowSelectionChange,
      };
    }
    return null;
  };

  const nextRowSelection = getRowSelectionConfig();

  useDeepEffect(() => {
    if (form) {
      form.query(LIST_FILED_CODE).take((target) => {
        target.setComponentProps({
          ...restProps,
          rowKey: tableRowKey,
          rowSelection: nextRowSelection,
          onTableChange: onChange,
          selectedRowKeys,
          setSelectedRowKeys,
          selectedRows,
          setSelectedRows,
          scrollY,
          pagination: {
            current: Number(currentPage),
            total,
            pageSize: Number(pageSize),
          },
        });
      });
    }
  }, [
    form?.id,
    currentPage,
    total,
    pageSize,
    onChange,
    tableRowKey,
    restProps,
    nextRowSelection,
    scrollY,
    selectedRowKeys,
    selectedRows,
  ]);

  return (
    <Skeleton loading={!!loading}>
      <FormProvider form={form}>
        <div
          className={`form-id-${form?.id}`}
          style={{
            height: '100%',
          }}
          ref={domRef}
        >
          {schema ? (
            <SchemaField schema={schema} components={components} />
          ) : (
            <Empty description="暂无数据" />
          )}
        </div>
      </FormProvider>
    </Skeleton>
  );
};

SchemeTableForm.defaultProps = {
  loading: false,
  rowKey: 'id',
};

export default memo(SchemeTableForm);

// packages/render-vue/src/scheme-table-form/SchemeTableForm.tsx
import { setValidateLanguage } from '@formily/core';

import { FormProvider } from '@/formily-vue';
import { computed, defineComponent, ref, toRef, onMounted, watchEffect, watch } from 'vue';
import { Empty, Skeleton } from 'ant-design-vue';

import { useNotifyDevtools } from '@/hooks';
import useCreateSchemaField from '@/hooks/useSchemaField';

import { SchemeTableFormProps, getSchemeTableFormProps } from './interface';

import useDOMRect from '@/hooks/dom/useDOMRect';
import { Key } from 'ant-design-vue/es/_util/type';
import { useItemKey } from '@/components/array-base';
import { toArray } from '@/utils';
import { LIST_FILED_CODE } from '@/utils/constant';

const SchemeTableForm = defineComponent({
  name: 'SchemeTableForm',
  inheritAttrs: false,
  props: getSchemeTableFormProps(),
  setup(props: SchemeTableFormProps) {
    const { components } = props;

    const dataSourceRef = toRef(props, 'dataSource');
    const formRef = toRef(props, 'form');
    const defaultSelectedRowsRef = toRef(props, 'selectedRows');

    const SchemaField = useCreateSchemaField();

    const [contentRect, domRef] = useDOMRect<HTMLDivElement>();

    useNotifyDevtools(toRef(props, 'form'));

    const selectedRowKeys = ref<Key[]>([]);

    const selectedRows = ref<any[]>([]);

    const setSelectedRows = (nextSelectedRows: any[]) => {
      selectedRows.value = nextSelectedRows;
    };

    const setSelectedRowKeys = (nextSelectedRowKeys: Key[]) => {
      selectedRowKeys.value = nextSelectedRowKeys;
    };

    watchEffect(() => {
      setValidateLanguage(props.language ?? 'zh-CN');
    });

    const scrollY = ref(450);

    const { getRecordKey } = useItemKey(true);

    const tableRowKey = (record: any) => {
      const { rowKey } = props;

      if (typeof rowKey === 'function') {
        return rowKey(record);
      }

      return record[rowKey] || getRecordKey(record);
    };

    watchEffect(() => {
      if (contentRect.value) {
        const { height } = contentRect.value;

        scrollY.value = height - 140;
      }
    });

    watchEffect(() => {
      const form = formRef.value;
      const dataSource = dataSourceRef.value;
      const { hasClearSelectedRows } = props;

      if (form.id) {
        form.setValuesIn(LIST_FILED_CODE, dataSource);

        if (hasClearSelectedRows) {
          setSelectedRows([]);
          setSelectedRowKeys([]);
        }
      }
    });

    watchEffect(() => {
      const defaultSelectedRows = defaultSelectedRowsRef.value;

      setSelectedRowKeys(defaultSelectedRows?.map((item: any) => tableRowKey(item)) || []);
      setSelectedRows(defaultSelectedRows || []);
    });

    const handleRowSelectionChange = (rowKeys: Key[], changeSelectedRows: any[], info) => {
      const {
        rowSelectionType,
        rowSelection,
        selectedRows: defaultSelectedRows,
        dataSource,
      } = props;

      if (rowSelectionType === 'radio') {
        setSelectedRows(changeSelectedRows);
        setSelectedRowKeys(rowKeys);

        // @ts-ignore
        rowSelection?.onChange?.(rowKeys, changeSelectedRows, info);
      } else {
        const allDataSourceKey =
          toArray(dataSource).map((item: any, index) => tableRowKey(item) || index) || [];

        // 更新旧值选中的数据
        const selectedRowsMap = toArray(defaultSelectedRows).map((item: any) => {
          const record = changeSelectedRows.find(
            (current) => tableRowKey(current) === tableRowKey(item),
          );
          if (record) {
            return record;
          }
          return item;
        });

        const nextSelectedRows = selectedRowsMap
          .filter((item: Record<string, any>) => !allDataSourceKey.includes(tableRowKey(item)))
          .concat(
            changeSelectedRows.filter((item) => allDataSourceKey.includes(tableRowKey(item))),
          );

        const nextSelectedRowKeys = nextSelectedRows.map((item: any) => tableRowKey(item));

        setSelectedRows(nextSelectedRows);

        setSelectedRowKeys(nextSelectedRowKeys);
        // @ts-ignore
        rowSelection?.onChange?.(nextSelectedRowKeys, nextSelectedRows, info);
      }
    };

    const getRowSelectionConfig = computed(() => {
      const { hasRowSelection, rowSelection, rowSelectionType } = props;
      if (hasRowSelection) {
        return {
          // @ts-ignore
          ...rowSelection,
          selectedRowKeys: selectedRowKeys.value,
          selectedRows: selectedRows.value,
          type: rowSelectionType ?? 'checkbox',
          onChange: handleRowSelectionChange,
        };
      }
      return null;
    });

    const setComponentProps = () => {
      const form = formRef.value;
      const { onChange, pageSize, currentPage, total, tableLoading, ...restProps } = props;

      form.query(LIST_FILED_CODE).take((target) => {
        target.setComponentProps({
          ...restProps,
          loading: tableLoading,
          rowKey: tableRowKey,
          rowSelection: getRowSelectionConfig.value,
          onTableChange: onChange,
          selectedRowKeys: selectedRowKeys.value,
          setSelectedRowKeys,
          selectedRows: selectedRows.value,
          setSelectedRows,
          scrollY: scrollY.value,
          pagination: {
            pageSize: Number(pageSize),
            current: Number(currentPage),
            total: Number(total),
          },
        });
      });
    };

    onMounted(() => {
      setComponentProps();
    });

    watch([getRowSelectionConfig, scrollY], () => {
      setComponentProps();
    });

    watch(
      () => {
        return {
          ...props,
        };
      },
      () => {
        setComponentProps();
      },
    );

    return () => {
      const { schema, form, loading } = props;

      return (
        <Skeleton loading={!!loading}>
          <FormProvider form={form}>
            <div
              class={`form-id-${form?.id}`}
              style={{
                height: '100%',
              }}
              ref={domRef}
            >
              {schema ? (
                <SchemaField schema={schema} components={components} />
              ) : (
                <Empty description="暂无数据" />
              )}
            </div>
          </FormProvider>
        </Skeleton>
      );
    };
  },
});

export default SchemeTableForm;
