// packages/render-vue/src/components/schema-fragment/index.tsx

import { defineComponent } from 'vue';
import { RecursionField ,observer} from '@/formily-vue';
import { getSchemaFragmentProps, SchemaFragmentProps } from './interface';

const Fragment = defineComponent({
  render() {
    return null;
  },
});

const SchemaFragment = observer<SchemaFragmentProps>(
  defineComponent({
    name: 'SchemaFragment',
    props: getSchemaFragmentProps(),
    inheritAttrs: false,
    setup(props: SchemaFragmentProps) {
      return () => {
        const { schemaSource } = props;

        return schemaSource.map((item) => {
          const { name, schema } = item;

          const nowSchema = {
            ...schema,
            'x-component': Fragment,
          };
          return <RecursionField key={name} name={name} schema={nowSchema} onlyRenderSelf />;
        });
      };
    },
  }),
);

export default SchemaFragment;

// packages/render-react/src/components/schema-fragment/index.tsx
import { FC, memo } from 'react';
import { RecursionField,ISchema } from '@formily/react';


interface SchemaSourceItem {
  name: string;
  schema: ISchema;
}

interface SchemaFragmentProps {
  schemaSource: SchemaSourceItem[];
}

const SchemaFragment: FC<SchemaFragmentProps> = ({ schemaSource }) => {
  return (
    <>
      {schemaSource.map((item) => {
        const { name, schema } = item;

        const nowSchema = {
          ...schema,
          'x-component': 'Fragment',
        };
        return <RecursionField key={name} name={name} schema={nowSchema} onlyRenderSelf />;
      })}
    </>
  );
};

export default memo(SchemaFragment);
