// packages/render/src/components/list-table/index.tsx
import { FC } from 'react';
import { Space, Table, TableProps } from 'antd';

import { observer, useField } from '@formily/react';

import { useArrayTableColumns, useArrayTableSources, useSchemaBtn } from '../hooks';
import ArrayBase from '../array-base';
import { ArrayField } from '@formily/core';
import SchemaFragment from '@/components/schema-fragment';
import { useListTableStyle } from '@/components/list-table/hooks';
import cls from 'classnames';
import { DEFAULT_TABLE_PAGINATION } from '@/utils/constant';

export interface ListTableProps extends TableProps<any> {
  scrollY?: number;
  onAdd?: () => void;
  onEdit?: (record: any, index: number) => void;
  onRemove?: (record: any, index: number) => void;
  rowKey?: string;
  onTableChange: TableProps<any>['onChange'];
}

const ListTable: FC<ListTableProps> = observer(
  ({ scrollY, onAdd, onEdit, onRemove, rowKey, onTableChange, pagination, ...restProps }) => {
    const field = useField<ArrayField>();
    const [warpSSR, hashId, prefixCls] = useListTableStyle();
    const dataSource = Array.isArray(field.value) ? field.value.slice() : [];
    const sources = useArrayTableSources();
    const columns = useArrayTableColumns(dataSource, sources);

    const btn = useSchemaBtn();

    const defaultRowKey = (record: any) => {
      return record[rowKey] ?? dataSource.indexOf(record);
    };

    return warpSSR(
      <div className={cls(prefixCls, hashId)}>
        <ArrayBase onAdd={onAdd} onEdit={onEdit} onRemove={onRemove}>
          <Table
            size="small"
            {...restProps}
            onChange={onTableChange}
            rowKey={defaultRowKey}
            title={
              btn
                ? () => {
                    return <Space>{btn}</Space>;
                  }
                : null
            }
            bordered
            columns={columns}
            dataSource={dataSource}
            scroll={{
              x: 'max-content',
              y: scrollY,
            }}
            pagination={{
              ...DEFAULT_TABLE_PAGINATION,
              size: 'small',
              ...pagination,
            }}
          />
          <SchemaFragment schemaSource={sources} />
        </ArrayBase>
      </div>,
    );
  },
);

export default ListTable;

// packages/render-vue/src/components/list-table/ListTable.tsx
import { defineComponent, VNode } from 'vue';
import type { ArrayField } from '@formily/core';

import { Table, Space } from 'ant-design-vue';

import { observer } from '@/utils/observer';
import { RecursionField, useField } from '@/formily-vue';

import { useArrayTableColumns, useArrayTableSources, useTableSchemaBtn } from '@/hooks';

import ArrayBase from '@/components/array-base/ArrayBase';
import SchemaFragment from '@/components/schema-fragment';
import { useItemKey } from '@/components/array-base/hooks';

import { useStylePrefixCls } from '@/components/style/hooks';
import { DEFAULT_TABLE_PAGINATION } from '@/utils/constant';
import { getListTableProps, ListTableProps } from '@/components/list-table/interface';

const ListTable = observer<ListTableProps>(
  defineComponent({
    name: 'ListTable',
    inheritAttrs: false,
    props: getListTableProps(),
    setup(props: ListTableProps) {
      const fieldRef = useField<ArrayField>();

      const prefixCls = useStylePrefixCls('list-table');

      const { getRecordKey } = useItemKey(true);

      const btn = useTableSchemaBtn();

      return () => {
        const {
          onRemove,
          onAdd,
          onCopy,
          onEdit,
          onDetail,
          onMoveUp,
          onMoveDown,
          scrollY,
          rowSelection,
          onTableChange,
          pagination,
          selectedRowKeys,
          setSelectedRowKeys,
          selectedRows,
          setSelectedRows,
        } = props;

        const field = fieldRef.value;
        const dataSource = Array.isArray(field.value) ? field.value.slice() : [];

        const defaultRowKey = (record: any) => {
          if (typeof props.rowKey === 'function') {
            return props.rowKey(record);
          }

          return record[props.rowKey] || getRecordKey(record);
        };

        const sources = useArrayTableSources();
        const columns = useArrayTableColumns(dataSource, sources);

        const renderTitle = () => {
          return btn ? <Space>{btn}</Space> : null;
        };

        const renderBodyCell = ({ record, index, column }) => {
          const { schema } = column;

          return (
            <ArrayBase.Item index={index} record={record}>
              <RecursionField schema={schema} name={index} onlyRenderProperties />
            </ArrayBase.Item>
          );
        };

        const slots: Record<string, (...args) => VNode> = {
          bodyCell: renderBodyCell,
        };

        if (btn) {
          slots.title = renderTitle;
        }

        return (
          <div class={prefixCls}>
            <ArrayBase
              onRemove={onRemove}
              onAdd={onAdd}
              onCopy={onCopy}
              onEdit={onEdit}
              onDetail={onDetail}
              onMoveUp={onMoveUp}
              onMoveDown={onMoveDown}
              selectedRowKeys={selectedRowKeys}
              setSelectedRowKeys={setSelectedRowKeys}
              selectedRows={selectedRows}
              setSelectedRows={setSelectedRows}
            >
              <Table
                bordered
                rowSelection={rowSelection}
                rowKey={defaultRowKey}
                size="small"
                columns={columns}
                dataSource={dataSource}
                scroll={{
                  x: 'max-content',
                  y: scrollY ?? 520,
                }}
                onChange={onTableChange}
                pagination={{
                  ...DEFAULT_TABLE_PAGINATION,
                  // @ts-ignore
                  ...pagination,
                }}
                v-slots={slots}
              />
              <SchemaFragment schemaSource={sources} />
            </ArrayBase>
          </div>
        );
      };
    },
  }),
);

export default ListTable;
