// example-vue/src/views/drawer/Drawer.vue
<template>
  <list-layout
    :action="apiUrl.page"
    :get-logic-config="getLogicConfig"
    :reload-flag="reloadFlag"
    :page-code="DrawerConfig.LIST"
    @add="handleAdd"
    @edit="handleEdit"
    @detail="handleDetail"
    @remove="handleRemove"
  />

  <drawer-page-form
    :get-logic-config="getLogicConfig"
    :options="drawerPageOptions"
    :visible="drawerVisible"
    :has-confirm-button="false"
    :extra-logic-params="logicParams"
    :form-config="formConfig"
    @close="handleDrawerClose"
  />
</template>

<script setup lang="ts">
import { ref } from "vue";

import {
  ListLayout,
  useReloadFlag,
  useOpen,
  getJsonMetaSchema,
  DrawerPageForm,
  SchemaPatternEnum,
} from "@formlogic/render-vue";

import type {
  TransformsSchemaOptions,
  FormConfigProps,
} from "@formlogic/render-vue";

import getLogicConfig from "@/low-code-meta/logic";

import { apiUrl, DrawerConfig, drawerDetail, drawerRemove } from "./service";

import { validateFormValues, formatFormValues } from "./hooks";

const [reloadFlag, refreshReloadFlag] = useReloadFlag();

const [drawerVisible, showDrawer, hiddenDrawer] = useOpen();

const drawerPageOptions = ref<TransformsSchemaOptions | null>(null);

const logicParams = ref({});
const formConfig = ref<FormConfigProps>({});

const handleDrawerClose = () => {
  hiddenDrawer();
};

const successCallback = () => {
  drawerPageOptions.value = null;
  refreshReloadFlag();
  hiddenDrawer();
};

const handleAdd = () => {
  showDrawer();

  formConfig.value = {};

  logicParams.value = {
    successCallback,
    action: apiUrl.create,
    extraParams: {},
    validateFormValues,
    formatFormValues,
  };

  getJsonMetaSchema(DrawerConfig.CREATE).then((metaSchema) => {
    drawerPageOptions.value = {
      metaSchema,
      hasGroup: true,
    };
  });
};

const getRecordDetail = (record: any) => {
  drawerDetail({ code: record.code }).then((res) => {
    const { data } = res;
    formConfig.value = {
      initialValues: data,
    };
  });
};

const handleEdit = (index: number, record: any) => {
  showDrawer();

  getRecordDetail(record);

  logicParams.value = {
    successCallback,
    action: apiUrl.update,
    extraParams: {},
    validateFormValues,
    formatFormValues,
  };

  getJsonMetaSchema(DrawerConfig.EDIT).then((metaSchema) => {
    drawerPageOptions.value = {
      metaSchema,
      hasGroup: true,
    };
  });
};

const handleDetail = (index: number, record: any) => {
  showDrawer();

  getRecordDetail(record);

  getJsonMetaSchema(DrawerConfig.DETAIL).then((metaSchema) => {
    drawerPageOptions.value = {
      metaSchema,
      hasGroup: true,
      pattern: SchemaPatternEnum.DETAIL,
    };
  });
};

const handleRemove = (index: number, record: any) => {
  const { code } = record || {};
  drawerRemove({ code }).then(() => {
    refreshReloadFlag();
  });
};
</script>

<style scope></style>

// example/src/pages/drawer/index.tsx
import { useState } from 'react';
import {
  DrawerPageForm,
  FormConfigProps,
  ListLayout,
  TransformsSchemaOptions,
  useJsonMetaSchema,
  useOpen,
  useReloadFlag,
  getJsonMetaSchema,
  SchemaPatternEnum,
} from '@formlogic/render';

import getLogicConfig from '@/low-code-meta/logic';

import { apiUrl, DrawerConfig, drawerRemove, drawerDetail } from './service';

import { formatFormValues, validateFormValues, components } from './hooks';

const DrawerList = () => {
  const { metaSchema } = useJsonMetaSchema(DrawerConfig.LIST);

  const [options, setOptions] = useState<TransformsSchemaOptions>(null);
  const [open, showDrawer, hiddenDrawer] = useOpen();

  const [formConfig, setFormConfig] = useState<FormConfigProps>({});

  const [reloadFlag, refreshReloadFlag] = useReloadFlag();

  const [action, setAction] = useState(apiUrl.create);

  const handleAddClick = () => {
    setAction(apiUrl.create);

    showDrawer();

    getJsonMetaSchema(DrawerConfig.CREATE).then((metaSchema) => {
      setOptions({
        metaSchema,
        hasGroup: true,
      });
    });
  };

  const handleRemoveClick = (index, record) => {
    const { code } = record || {};
    drawerRemove({ code }).then(() => {
      refreshReloadFlag();
    });
  };

  const handleEditClick = (index, record) => {
    setAction(apiUrl.update);
    showDrawer();

    getJsonMetaSchema(DrawerConfig.EDIT).then((metaSchema) => {
      setOptions({
        metaSchema,
        hasGroup: true,
      });
    });

    const { code } = record || {};
    drawerDetail({ code }).then((res) => {
      const { data } = res;
      setFormConfig({
        initialValues: data,
      });
    });
  };

  const handleDetailClick = (index, record) => {
    setAction('');
    showDrawer();

    getJsonMetaSchema(DrawerConfig.DETAIL).then((metaSchema) => {
      setOptions({
        metaSchema,
        hasGroup: true,
        pattern: SchemaPatternEnum.DETAIL,
      });
    });

    const { code } = record || {};
    drawerDetail({ code }).then((res) => {
      const { data } = res;
      setFormConfig({
        initialValues: data,
      });
    });
  };

  const successCallback = () => {
    setOptions(null);
    refreshReloadFlag();
    hiddenDrawer();
  };

  return (
    <>
      <ListLayout
        getLogicConfig={getLogicConfig}
        metaSchema={metaSchema}
        action={apiUrl.page}
        reloadFlag={reloadFlag}
        onEdit={handleEditClick}
        onAdd={handleAddClick}
        onRemove={handleRemoveClick}
        onDetail={handleDetailClick}
      />

      <DrawerPageForm
        open={open}
        options={options}
        onClose={hiddenDrawer}
        getLogicConfig={getLogicConfig}
        formConfig={formConfig}
        extraLogicParams={{
          successCallback,
          action,
          extraParams: {},
          validateFormValues,
          formatFormValues,
        }}
        components={components}
        hasConfirmButton={false}
      />
    </>
  );
};

export default DrawerList;
