// packages/render-vue/src/components/layout/index.tsx
import { defineComponent } from 'vue';
import { useStylePrefixCls } from '@/components/style/hooks';
import { Spin } from 'ant-design-vue';
import cls from 'classnames';
import { getLayoutProps } from '@/components/layout/interface';

const Layout = defineComponent({
  name: 'Layout',
  props: getLayoutProps(),
  slots: ['header', 'footer'],
  setup(props, { slots }) {
    const prefixCls = useStylePrefixCls('layout');

    return () => {
      const { loading, style, height } = props;

      const renderHeader = () => {
        if (!slots.header) {
          return null;
        }

        return <div class={cls(`${prefixCls}-header`)}>{slots.header()}</div>;
      };

      const renderFooter = () => {
        if (!slots.footer) {
          return null;
        }

        return <div class={cls(`${prefixCls}-footer`)}>{slots.footer()}</div>;
      };

      return (
        <Spin spinning={loading}>
          <div
            class={cls(props.class, prefixCls, `${prefixCls}-wrapper`)}
            style={{ ...style, height }}
          >
            {renderHeader()}
            <div class={cls(`${prefixCls}-body`)}>{slots?.default()}</div>
            {renderFooter()}
          </div>
        </Spin>
      );
    };
  },
});

export default Layout

// packages/component/src/layout/index.tsx
import { CSSProperties, FC, PropsWithChildren, ReactNode } from 'react';

import { useLayoutStyle } from '@/layout/hooks';
import cls from 'classnames';
import PageLoading from '@/page-loading';

export interface LayoutProps extends PropsWithChildren {
  footer?: ReactNode;
  header?: ReactNode;
  className?: string;
  style?: CSSProperties;
  height?: number | string;
  loading?: boolean;
}

const Layout: FC<LayoutProps> = ({
  header,
  loading,
  footer,
  children,
  className,
  height,
  style,
}) => {
  const [warpSSR, hashId, prefixCls] = useLayoutStyle();

  const renderHeader = () => {
    if (!header) {
      return null;
    }

    return <div className={cls(`${prefixCls}-header`, hashId)}>{header}</div>;
  };

  const renderFooter = () => {
    if (!footer) {
      return null;
    }

    return <div className={cls(`${prefixCls}-footer`, hashId)}>{footer}</div>;
  };

  return warpSSR(
    <PageLoading loading={loading}>
      <div
        className={cls(className, hashId, prefixCls, `${prefixCls}-wrapper`)}
        style={{ ...style, height }}
      >
        {renderHeader()}
        <div className={cls(`${prefixCls}-body`, hashId)}>{children}</div>
        {renderFooter()}
      </div>
    </PageLoading>,
  );
};

export default Layout;
