// packages/render-vue/src/components/page-loading/PageLoading.tsx
import { defineComponent } from 'vue';
import { Spin } from 'ant-design-vue';
import { useStylePrefixCls } from '@/components/style/hooks';
import { getPageLoadingProps, PageLoadingProps } from './interface';

const PageLoading = defineComponent({
  name: 'PageLoading',
  inheritAttrs: false,
  props: getPageLoadingProps(),
  setup(props: PageLoadingProps, { slots }) {
    return () => {
      const prefixCls = useStylePrefixCls('page-loading');

      const { loading } = props;

      return (
        <Spin spinning={loading} wrapperClassName={prefixCls}>
          {slots.default()}
        </Spin>
      );
    };
  },
});

export default PageLoading;

// packages/component/src/page-loading/index.tsx
import { usePageLoadingStyleStyle } from '@/page-loading/hooks';
import { Spin, SpinProps } from 'antd';
import { FC, PropsWithChildren } from 'react';
import cls from 'classnames';

export interface PageLoadingProps extends Omit<SpinProps, 'spinning'>, PropsWithChildren {
  loading?: boolean;
}

const PageLoading: FC<PageLoadingProps> = ({
  children,
  loading,
  wrapperClassName,
  ...restProps
}) => {
  const [warpSSR, hashId, prefixCls] = usePageLoadingStyleStyle();

  return warpSSR(
    <Spin
      {...restProps}
      spinning={loading ?? false}
      wrapperClassName={cls(wrapperClassName, prefixCls, hashId)}
    >
      {children}
    </Spin>,
  );
};

export default PageLoading;
