// packages/render-vue/src/components/left-right-slot/index.tsx
import { Col, Row,  Space } from 'ant-design-vue';

import cls from 'classnames';
import { defineComponent } from 'vue';
import { useStylePrefixCls } from '@/components/style/hooks';
import { rowProps } from 'ant-design-vue/es/grid/Row';

const LeftRightSlot = defineComponent({
  name: 'LeftRightSlot',
  props: rowProps(),
  slots: ['left', 'right'],
  setup(props, { slots }) {
    const prefixCls = useStylePrefixCls('left-right-slot');
    return () => {
      return (
        <Row gutter={12} {...props} class={cls(prefixCls)}>
          <Col span={12} class={cls(`${prefixCls}-left`)}>
            <Space>{slots.left?.()}</Space>
          </Col>
          <Col span={12} class={cls(`${prefixCls}-right`)}>
            <Space>{slots.right?.()}</Space>
          </Col>
        </Row>
      );
    };
  },
});

export default LeftRightSlot;

// packages/component/src/left-right-slot/index.tsx
import { Col, Row, RowProps, Space } from 'antd';
import { FC, ReactNode } from 'react';
import { useLeftRightSlotStyle } from '@/left-right-slot/hooks';
import cls from 'classnames';

export interface LeftRightSlotProps extends RowProps {
  left?: ReactNode;
  right?: ReactNode;
}

const LeftRightSlot: FC<LeftRightSlotProps> = ({ left, right, className, ...rowProps }) => {
  const [warpSSR, hashId, prefixCls] = useLeftRightSlotStyle();

  return warpSSR(
    <Row gutter={12} {...rowProps} className={cls(hashId, className, prefixCls)}>
      <Col span={12} className={cls(hashId, `${prefixCls}-left`)}>
        <Space>{left}</Space>
      </Col>
      <Col span={12} className={cls(hashId, `${prefixCls}-right`)}>
        <Space>{right}</Space>
      </Col>
    </Row>,
  );
};

export default LeftRightSlot;
