// packages/render-vue/src/components/draggable-modal/ModalRender.tsx
import { computed, CSSProperties, defineComponent, ref, watch, watchEffect } from 'vue';
import cls from 'classnames';
import { DragOutlined } from '@ant-design/icons-vue';
import useDOMHover from '@/hooks/dom/useDOMHover';
import { useStylePrefixCls } from '@/components/style/hooks';

import { Teleport } from 'vue';
import { getModalRenderProps } from './interface';
import { useDraggable } from '@vueuse/core';

const ModalRender = defineComponent({
  name: 'ModalRender',
  props: getModalRenderProps(),

  setup(props, { slots }) {
    const [hover, domHoverRef] = useDOMHover();

    const portalContainer = ref();

    const draggableRef = ref<HTMLDivElement>(null);

    const prefixCls = useStylePrefixCls('draggable-modal-render');

    watchEffect(() => {
      if (draggableRef.value) {
        portalContainer.value = draggableRef.value.querySelector('.ant-modal-content');
      }
    });

    const { x, y, isDragging } = useDraggable(domHoverRef);

    const startX = ref<number>(0);
    const startY = ref<number>(0);
    const startedDrag = ref(false);
    const transformX = ref(0);
    const transformY = ref(0);
    const preTransformX = ref(0);
    const preTransformY = ref(0);
    const dragRect = ref({ left: 0, right: 0, top: 0, bottom: 0 });
    watch([x, y], () => {
      if (!startedDrag.value) {
        startX.value = x.value;
        startY.value = y.value;
        const bodyRect = document.body.getBoundingClientRect();
        const titleRect = domHoverRef.value.getBoundingClientRect();
        dragRect.value.right = bodyRect.width - titleRect.width;
        dragRect.value.bottom = bodyRect.height - titleRect.height;
        preTransformX.value = transformX.value;
        preTransformY.value = transformY.value;
      }
      startedDrag.value = true;
    });
    watch(isDragging, () => {
      if (!isDragging) {
        startedDrag.value = false;
      }
    });

    watchEffect(() => {
      if (startedDrag.value) {
        transformX.value =
          preTransformX.value +
          Math.min(Math.max(dragRect.value.left, x.value), dragRect.value.right) -
          startX.value;
        transformY.value =
          preTransformY.value +
          Math.min(Math.max(dragRect.value.top, y.value), dragRect.value.bottom) -
          startY.value;
      }
    });

    const transformStyle = computed<CSSProperties>(() => {
      return {
        transform: `translate(${transformX.value}px, ${transformY.value}px)`,
      };
    });

    return () => {
      const { hasDrag } = props;

      return (
        <div ref={draggableRef} style={transformStyle.value}>
          {hasDrag && portalContainer.value ? (
            <Teleport to={portalContainer.value}>
              <DragOutlined ref={domHoverRef} class={cls(`${prefixCls}-drag`)} />
            </Teleport>
          ) : null}

          {slots.default()}
        </div>
      );
    };
  },
});

export default ModalRender;

// packages/component/src/draggable-modal/ModalRender.tsx
import { FC, ReactNode, useRef, useState, useEffect } from 'react';

import Draggable, { DraggableEvent, DraggableData } from 'react-draggable';
import { useDraggableModalStyle } from '@/draggable-modal/hooks';
import cls from 'classnames';

import Portal from '@rc-component/portal';

import { DragOutlined } from '@ant-design/icons';
import { useDOMHover } from '@/hooks';

export interface ModalRenderProps {
  hasDrag?: boolean;
  modal: ReactNode;
  dragClassName?: string;
}

const ModalRender: FC<ModalRenderProps> = ({ hasDrag, dragClassName, modal }) => {
  const [bounds, setBounds] = useState({ left: 0, top: 0, bottom: 0, right: 0 });
  const draggableRef = useRef<HTMLDivElement>(null);

  const [warpSSR, hashId, prefixCls] = useDraggableModalStyle();

  const [draggableDisabled, setDraggableDisabled] = useState(false);

  const [hover, domHoverRef] = useDOMHover();

  const [portalContainer, setPortalContainer] = useState(null);

  const handleStart = (_event: DraggableEvent, uiData: DraggableData) => {
    const { clientWidth, clientHeight } = document.documentElement;
    const targetRect = draggableRef.current?.getBoundingClientRect();
    if (!targetRect) {
      return;
    }
    setBounds({
      left: -targetRect.left + uiData.x,
      right: clientWidth - (targetRect.right - uiData.x),
      top: -targetRect.top + uiData.y,
      bottom: clientHeight - (targetRect.bottom - uiData.y),
    });
  };

  useEffect(() => {
    if (draggableRef.current) {
      setPortalContainer(draggableRef.current.querySelector('.ant-modal-content'));
    }
  }, []);

  useEffect(() => {
    setDraggableDisabled(!hover);
  }, [hover]);

  return warpSSR(
    <Draggable nodeRef={draggableRef} disabled={draggableDisabled} bounds={bounds} onStart={handleStart}>
      <div ref={draggableRef}>
        {hasDrag ? (
          <Portal open getContainer={portalContainer}>
            <DragOutlined
              ref={domHoverRef}
              className={cls(hashId, dragClassName, `${prefixCls}-drag`)}
            />
          </Portal>
        ) : null}

        {modal}
      </div>
    </Draggable>,
  );
};

export default ModalRender;
