// packages/render/src/components/form-tabs-group/index.tsx
import { FC, PropsWithChildren, useEffect, useState } from 'react';
import { Card, Tabs } from 'antd';
import { useField, RecursionField, observer } from '@formily/react';
import FeedbackBadge from '@/components/feedback-badge';
import { usePropertiesSources } from '@/components/hooks';
import SchemaFragment from '@/components/schema-fragment';
import { useFormTabsGroupStyle } from '@/components/form-tabs-group/hooks';
import cls from 'classnames';

interface FormTabsGroupProps extends PropsWithChildren {
  activeKey?: string;
  onChange?: (activeKey: string) => void;
}

const useTabs = (tabsSources) => {
  const tabsField = useField();

  return tabsSources.reduce((tabs, cur) => {
    const { name, title, schema } = cur || {};

    const field = tabsField.query(tabsField.address.concat(name)).take();

    if (field?.display !== 'visible') {
      return tabs;
    }

    return tabs.concat({
      name,
      title,
      key: `${name}`,
      schema,
    });
  }, []);
};

const FormTabsGroup: FC<FormTabsGroupProps> = observer(({ activeKey: propActiveKey, onChange }) => {
  const tabsSources = usePropertiesSources();

  const tabs = useTabs(tabsSources);

  const defaultKey = `${tabs[0]?.key}`;

  const [warpSSR, hashId, prefixCls] = useFormTabsGroupStyle();

  const [activeKey, setActiveKey] = useState(() => {
    return defaultKey;
  });

  useEffect(() => {
    setActiveKey(propActiveKey);
  }, [propActiveKey]);

  const existIndex = tabs.findIndex((cur) => cur.key === activeKey);

  useEffect(() => {
    if (existIndex === -1) {
      setActiveKey(defaultKey);
    }
  }, [existIndex, defaultKey]);

  const handleChange = (nextActiveKey) => {
    setActiveKey(nextActiveKey);
    onChange?.(nextActiveKey);
  };

  return warpSSR(
    <div className={cls(prefixCls, hashId)}>
      <Tabs
        activeKey={activeKey}
        onChange={handleChange}
        type="card"
        items={tabs.map((item) => {
          const { schema, key, name, title } = item || {};
          return {
            key,
            label: <FeedbackBadge name={name}>{title}</FeedbackBadge>,
            forceRender: true,
            children: (
              <Card size="small" id={key}>
                <RecursionField schema={schema} name={name} onlyRenderProperties />
              </Card>
            ),
          };
        })}
      />

      <SchemaFragment schemaSource={tabsSources} />
    </div>,
  );
});

export default FormTabsGroup;

// packages/render-vue/src/components/form-tabs-group/FormTabsGroup.tsx
import { defineComponent, ref, watch } from 'vue';
import cls from 'classnames';
import SchemaFragment from '@/components/schema-fragment';
import { useStylePrefixCls } from '@/components/style/hooks';

import { Card, Tabs } from 'ant-design-vue';
import { RecursionField } from '@/formily-vue';
import { usePropertiesSources } from '@/hooks';
import { useTabs } from '@/components/form-tabs-group/hooks';
import FeedbackBadge from '@/components/feedback-badge';
import { observer } from '@/formily-vue';
import { FormTabsGroupProps, getFormTabsGroupProps } from '@/components/form-tabs-group/interface';

const FormTabsGroup = observer<FormTabsGroupProps>(
  defineComponent({
    name: 'FormTabsGroup',
    inheritAttrs: false,
    props: getFormTabsGroupProps(),
    setup(props: FormTabsGroupProps) {
      const prefixCls = useStylePrefixCls('form-tabs-group');

      const activeKey = ref(null);


      watch(
        () => props.activeKey,
        (nextActiveKey) => {
          activeKey.value = nextActiveKey;
        },
      );

      const handleChange = (nextActiveKey:string) => {
        activeKey.value = nextActiveKey;
        props.onChange?.(nextActiveKey);
      };

      return () => {
        const tabsSources = usePropertiesSources();

        const tabs = useTabs(tabsSources);

        const defaultKey = `${tabs[0]?.key}`;

        return (
          <div class={cls(prefixCls)}>
            <SchemaFragment schemaSource={tabsSources} />
            <Tabs activeKey={activeKey.value || defaultKey} onChange={handleChange} type="card">
              {tabs.map((item) => {
                const { schema, key, name, title } = item || {};

                return (
                  <Tabs.TabPane
                    key={key}
                    id={key}
                    v-slots={{
                      tab: () => {
                        return <FeedbackBadge name={name}>{title}</FeedbackBadge>;
                      },
                    }}
                    forceRender
                  >
                    <Card size="small">
                      <RecursionField schema={schema} name={name} onlyRenderProperties />
                    </Card>
                  </Tabs.TabPane>
                );
              })}
            </Tabs>
          </div>
        );
      };
    },
  }),
);

export default FormTabsGroup;
