// packages/render-vue/src/scheme-form/SchemeForm.tsx
import { setValidateLanguage } from '@formily/core';

import { FormProvider } from '@/formily-vue';
import { defineComponent, ref, toRef, watch, watchEffect } from 'vue';
import { Empty, Skeleton } from 'ant-design-vue';

import { useNotifyDevtools } from '@/hooks';
import useCreateSchemaField from '@/hooks/useSchemaField';

import { clone } from '@formily/shared';

import { SchemeFormProps, schemeFormProps } from '@/scheme-form/interface';
import { provideSchemeForm } from '@/scheme-form/hooks';
import 'ant-design-vue/dist/antd.css';

const SchemeForm = defineComponent({
  name: 'SchemeForm',
  inheritAttrs: false,
  props: schemeFormProps,
  setup(props: SchemeFormProps) {
    const {
      getLogicConfig,
      extraLogicParams,
      events,
      pattern,
      loading: propsLoading,
      components,
    } = props;

    const SchemaField = useCreateSchemaField();


    useNotifyDevtools(toRef(props, 'form'));

    watchEffect(() => {
      setValidateLanguage(props.language ?? 'zh-CN');
    });

    let loading = !!propsLoading;

    const schemeFormRef = ref({
      pattern,
      getLogicConfig,
      extraLogicParams,
      events,
    });

    watch(
      () => {
        return {
          pattern: props.pattern,
          getLogicConfig: props.getLogicConfig,
          extraLogicParams: props.extraLogicParams,
          events: props.events,
        };
      },
      (nextSchemeFormRef) => {
        schemeFormRef.value = nextSchemeFormRef;
      },
    );

    provideSchemeForm(schemeFormRef);

    return () => {
      const { schema, form } = props;

      return (
        <Skeleton loading={loading}>
          <FormProvider form={form}>
            <form class={`form-id-${form?.id}`}>
              {schema ? (
                <SchemaField schema={clone(schema)} components={components ?? {}} />
              ) : (
                <Empty description="暂无数据" />
              )}
            </form>
          </FormProvider>
        </Skeleton>
      );
    };
  },
});

export default SchemeForm;

// packages/render/src/scheme-form/index.tsx
import { FC, memo, useEffect } from 'react';
import { Form, setValidateLanguage } from '@formily/core';
import { FormProvider } from '@formily/react';
import { ISchema } from '@formily/react';

import { Empty, Skeleton } from 'antd';

import { useNotifyDevtools } from '@/hooks';
import useCreateSchemaField from '@/hooks/useSchemaField';

import { SchemeFormContent, SchemeFormValueContent } from '@/scheme-form/hooks';

import { clone } from '@formily/shared';
import { Components } from '@/interface';

export interface SchemeFormProps extends SchemeFormValueContent {
  language?: string;
  schema: ISchema;
  loading?: boolean;
  form: Form;
  components?: Components;
}

const SchemeForm: FC<SchemeFormProps> = ({
  getLogicConfig,
  extraLogicParams,
  events,
  pattern,
  loading: propsLoading,
  language,
  schema,
  components,
  form,
}) => {
  const SchemaField = useCreateSchemaField();

  useNotifyDevtools(form);

  useEffect(() => {
    setValidateLanguage(language ?? 'zh-CN');
  }, [language]);

  const loading = !!propsLoading;

  return (
    <>
      <Skeleton loading={loading}>
        <FormProvider form={form}>
          <SchemeFormContent.Provider
            value={{
              pattern,
              getLogicConfig,
              extraLogicParams,
              events,
            }}
          >
            <form className={`form-id-${form.id}`}>
              {schema ? (
                <SchemaField schema={clone(schema)} components={components ?? {}} />
              ) : (
                <Empty description="暂无数据" />
              )}
            </form>
          </SchemeFormContent.Provider>
        </FormProvider>
      </Skeleton>
    </>
  );
};

SchemeForm.defaultProps = {
  loading: false,
};

export default memo(SchemeForm);
