// packages/render/src/components/array-drawer-table/index.tsx
import { FC, useState } from 'react';
import { useJsonMetaSchema, useOpen, useSchemaComponentsContext } from '@/hooks';

import DrawerPageForm from '@/drawer-page-form';
import { observer, useField } from '@formily/react';

import ArrayTableBase, { ArrayTableBaseProps } from '@/components/array-table-base';
import { IFormProps, isArrayField } from '@formily/core';
import { AnyObject } from '@formlogic/component';
import { TransformsSchemaOptions } from '@/transforms';
import { useSchemeFormContent } from '@/scheme-form/hooks';

export interface ArrayDrawerTableProps extends Omit<ArrayTableBaseProps, 'onEdit' | 'onAdd'> {
  drawerPageCode?: string;
  drawerFormConfig?: IFormProps;
  drawerExtraLogicParams?: AnyObject;
}

const ArrayDrawerTable: FC<ArrayDrawerTableProps> = observer(
  ({ drawerPageCode, drawerFormConfig, drawerExtraLogicParams, ...restProps }) => {
    const [open, showOpen, hiddenOpen] = useOpen();

    const [activeIndex, setActiveIndex] = useState(-1);

    const [formConfig, setFormConfig] = useState<IFormProps>({});

    const {metaSchema} = useJsonMetaSchema(drawerPageCode);

    const field = useField();

    const components = useSchemaComponentsContext();

    const { getLogicConfig } = useSchemeFormContent();

    const [options, setOptions] = useState<TransformsSchemaOptions>({
      metaSchema: null,
      hasGroup: true,
    });

    const genOptions = () => {
      setOptions({
        metaSchema,
        hasGroup: true,
      });
    };

    const genFormConfig = (otherConfig: IFormProps) => {
      setFormConfig({
        ...drawerFormConfig,
        ...otherConfig,
      });
    };

    const handleEdit = (index, record) => {
      setActiveIndex(index);

      genOptions();
      genFormConfig({
        values: record,
        initialValues: record,
      });

      showOpen();
    };

    const handleAdd = () => {
      setActiveIndex(-1);
      genOptions();
      genFormConfig({
        initialValues: {},
      });

      showOpen();
    };

    const handleClose = () => {
      hiddenOpen();
    };

    const handleConfirm = (formValues) => {
      if (isArrayField(field)) {
        if (activeIndex === -1) {
          field.push(formValues).then(() => void 0);
        } else {
          field.value.splice(activeIndex, 1, formValues);

          field.onInput(field.value).then(() => void 0);
        }
      }
    };

    return (
      <>
        <ArrayTableBase {...restProps} onAdd={handleAdd} onEdit={handleEdit} />

        <DrawerPageForm
          open={open}
          options={options}
          onClose={handleClose}
          onConfirm={handleConfirm}
          formConfig={formConfig}
          extraLogicParams={drawerExtraLogicParams}
          getLogicConfig={getLogicConfig}
          components={components}
        />
      </>
    );
  },
);

export default ArrayDrawerTable;

// packages/render-vue/src/components/array-drawer-table/ArrayDrawerTable.tsx

import { defineComponent, ref, toRef } from 'vue';
import ArrayTableBase from '@/components/array-table-base';
import DrawerPageForm from '@/drawer-page-form';
import { useField, useSchemaComponentsContext,observer } from '@/formily-vue';
import { useSchemeFormContent } from '@/scheme-form';
import { useJsonMetaSchema } from '@/hooks';
import { SchemaPattern } from '@/interface';
import { TransformsSchemaOptions } from '@/transforms';
import { IFormProps, isArrayField } from '@formily/core';
import {getArrayDrawerTableProps} from "./interface";

const ArrayDrawerTable = observer(
  defineComponent({
    name: 'ArrayDrawerTable',
    inheritAttrs: false,
    props: getArrayDrawerTableProps(),
    setup(props) {
      const visible = ref(false);
      const options = ref<TransformsSchemaOptions>(null);
      const formConfig = ref<IFormProps>({});
      const activeIndex = ref(-1);

      const fieldRef = useField();

      const { metaSchema } = useJsonMetaSchema(toRef(props, 'drawerPageCode'));

      const genOptions = (pattern?: SchemaPattern) => {
        options.value = {
          metaSchema: metaSchema.value,
          hasGroup: true,
          pattern,
        };
      };

      const genFormConfig = (otherConfig: IFormProps) => {
        const { drawerFormConfig } = props;
        formConfig.value = {
          ...drawerFormConfig,
          ...otherConfig,
        };
      };

      const handleClose = () => {
        visible.value = false;
      };

      const handleAdd = () => {
        visible.value = true;
      };

      const handleEdit = (index, record) => {
        activeIndex.value = index;

        genOptions();
        genFormConfig({
          values: record,
          initialValues: record,
        });

        visible.value = true;
      };

      const handleDetail = (index, record) => {
        activeIndex.value = index;

        genOptions('DETAIL');
        genFormConfig({
          values: record,
          initialValues: record,
        });

        visible.value = true;
      };

      const handleConfirm = (formValues) => {
        const field = fieldRef.value;

        if (isArrayField(field)) {
          if (activeIndex.value === -1) {
            field.push(formValues).then(() => void 0);
          } else {
            field.value.splice(activeIndex.value, 1, formValues);

            field.onInput(field.value).then(() => void 0);
          }
        }
      };

      const componentsRef = useSchemaComponentsContext();

      const formContentRef = useSchemeFormContent();

      return () => {
        const { drawerExtraLogicParams, ...restProps } = props;

        const { getLogicConfig } = formContentRef.value;

        return (
          <>
            <ArrayTableBase
              {...restProps}
              onDetail={handleDetail}
              onAdd={handleAdd}
              onEdit={handleEdit}
            />

            <DrawerPageForm
              visible={visible.value}
              options={options.value}
              onClose={handleClose}
              onConfirm={handleConfirm}
              formConfig={formConfig.value}
              extraLogicParams={drawerExtraLogicParams}
              getLogicConfig={getLogicConfig}
              components={componentsRef.value}
            />
          </>
        );
      };
    },
  }),
);

export default ArrayDrawerTable;
