// packages/render-vue/src/components/popover-btn/PopoverBtn.tsx
import { defineComponent, ref } from 'vue';
import { Button, Popover } from 'ant-design-vue';
import { RecursionField, useField, useFieldSchema } from '@/formily-vue';
import { MenuOutlined } from '@ant-design/icons-vue';

const PopoverBtn = defineComponent({
  name: 'PopoverBtn',
  inheritAttrs: false,
  setup() {
    const schema = useFieldSchema();

    const openRef = ref(false);

    const field = useField();

    const handleOpenChange = (nextOpen: boolean) => {
      openRef.value = nextOpen;
    };

    return () => {
      return (
        <Popover
          content={
            <RecursionField
              schema={schema.value}
              onlyRenderProperties
              basePath={field.value.address}
            />
          }
          trigger="hover"
          visible={openRef.value}
          onVisibleChange={handleOpenChange}
        >
          <Button
            v-slots={{
              icon: () => <MenuOutlined />,
            }}
            type="text"
            size="small"
          />
        </Popover>
      );
    };
  },
});

export default PopoverBtn;

// packages/render-react/src/components/popover-btn/index.tsx
import { observer, RecursionField, useField, useFieldSchema } from '@formily/react';
import { Popover, Button } from 'antd';
import { MenuOutlined } from '@ant-design/icons';
import { FC, useState } from 'react';

export interface PopoverBtnProps {}

const PopoverBtn: FC<PopoverBtnProps> = observer(() => {
  const schema = useFieldSchema();

  const [open, setOpen] = useState(false);

  const field = useField();

  const handleOpenChange = (nextOpen: boolean) => {
    setOpen(nextOpen);
  };

  return (
    <Popover
      content={<RecursionField schema={schema} onlyRenderProperties basePath={field.address} />}
      trigger="hover"
      open={open}
      onOpenChange={handleOpenChange}
    >
      <Button icon={<MenuOutlined />} type="text" size="small" />
    </Popover>
  );
});

export default PopoverBtn;
