// packages/render-react/src/modal-page-form/index.tsx
import { message } from 'antd';
import SchemeForm, { SchemeFormProps } from '@/scheme-form';
import { FC, useEffect, useState, MouseEvent, useMemo } from 'react';

import { TransformsSchemaOptions } from '@/transforms';
import { AnyObject, EventsObject, LogicConfig, SchemaPatternEnum } from '@/interface';
import { usePageForm, useTriggerLogic } from '@/hooks';

import { PageLoading, DraggableModal, DraggableModalProps } from '@formlogic/component';
import { getSubmitFormValues } from '@/utils/formUtils';
import { Form, IFormProps } from '@formily/core';
import { ClickRecord } from '@/components/buttons';
import DrawerModalFooter from '@/components/drawer-modal-footer';

export interface ModalPageFormProps
  extends Omit<DraggableModalProps, 'onCancel' | 'onOk'>,
    Pick<SchemeFormProps, 'language' | 'components'> {
  options: TransformsSchemaOptions;
  getLogicConfig: LogicConfig;
  formConfig?: IFormProps;
  extraLogicParams?: AnyObject;
  events?: EventsObject;
  validateFormValues?: (formValues: any) => Promise<string>;
  onConfirm?: (formValues: any) => void;
  onClose?: (e: MouseEvent<HTMLButtonElement>) => void;
  onFormMount?: (form: Form) => void;
  hasConfirmButton?: boolean;
}

const ModalPageForm: FC<ModalPageFormProps> = ({
  formConfig,
  onFormMount,
  options,
  getLogicConfig,
  events,
  extraLogicParams,
  onConfirm,
  onClose,
  validateFormValues,
  open,
  title,
  components,
  width,
  language,
  hasConfirmButton,
}) => {
  const [submitLoading, setSubmitLoading] = useState(false);

  const { schema, buttons, form, formLoading, pattern, refreshForm } = usePageForm({
    formConfig,
    onFormMount,
    options,
    getLogicConfig,
    logicParams: extraLogicParams,
    events,
    autoRefreshForm: false,
  });

  const [loadingDone, setLoadingDone] = useState(false);

  const [triggerLogic] = useTriggerLogic(getLogicConfig, () => {
    setSubmitLoading(false);
  });

  const handleCloseClick = (e) => {
    onClose?.(e);
  };

  const submit = (formValues: any) => {
    onConfirm?.(formValues);

    setSubmitLoading(false);
  };

  const handleConfirmClick = () => {
    setSubmitLoading(true);

    getSubmitFormValues(form)
      .then((formValues) => {
        if (validateFormValues) {
          validateFormValues(formValues)
            .then(() => {
              submit(formValues);
            })
            .catch((err) => {
              setSubmitLoading(false);
              if (err) {
                message.warning(err).then(() => void 0);
              }
            });
        } else {
          submit(formValues);
        }
      })
      .catch(() => {
        setSubmitLoading(false);
      });
  };

  const handleButtonItemClick = (e, record: ClickRecord) => {
    const { eventCode, clickCodes, code } = record;

    if (events?.[eventCode]) {
      return events[eventCode](e, {
        form,
        setSubmitLoading,
        code,
      });
    }

    if (clickCodes.length) {
      setSubmitLoading(true);

      triggerLogic(clickCodes, {
        params: extraLogicParams,
        form,
        effectHook: 'onClick',
        fieldCode: code,
        pageCode: options?.metaSchema?.code,
      });
    }
  };

  const loading = useMemo(() => {
    return formLoading || !open || !loadingDone;
  }, [formLoading, open, loadingDone]);

  useEffect(() => {
    if (open) {
      setSubmitLoading(false);
      refreshForm(formConfig);
    }
  }, [open, formConfig]);

  const handleAfterClose = () => {
    setLoadingDone(false);
  };

  useEffect(() => {
    let timer = null;

    if (open) {
      timer = requestIdleCallback(
        () => {
          setLoadingDone(true);
        },
        { timeout: 1000 },
      );
    }

    return () => {
      cancelIdleCallback(timer);
    };
  }, [open]);

  return (
    <DraggableModal
      title={title || '请填写'}
      maskClosable={false}
      open={open}
      confirmLoading={submitLoading}
      onOk={handleConfirmClick}
      onCancel={handleCloseClick}
      closable={false}
      width={width || '60%'}
      bodyStyle={{
        overflowY: 'auto',
        maxHeight: 500,
        minHeight: 200,
      }}
      footer={
        <DrawerModalFooter
          buttons={buttons}
          hasConfirmButton={hasConfirmButton ?? options?.pattern !== SchemaPatternEnum.DETAIL}
          onClick={handleButtonItemClick}
          onConfirmClick={handleConfirmClick}
          onCloseCLick={handleCloseClick}
          loading={submitLoading}
          disabled={submitLoading}
          components={components}
        />
      }
      destroyOnClose
      afterClose={handleAfterClose}
    >
      <PageLoading loading={submitLoading}>
        <SchemeForm
          form={form}
          loading={loading}
          schema={schema}
          components={components}
          pattern={pattern}
          getLogicConfig={getLogicConfig}
          events={events}
          extraLogicParams={extraLogicParams}
          language={language}
        />
      </PageLoading>
    </DraggableModal>
  );
};

export default ModalPageForm;

// packages/render-vue/src/modal-page-form/ModalPageForm.tsx
import { computed, defineComponent, ref, watch } from 'vue';

import DraggableModal from '@/components/draggable-modal';
import DrawerModalFooter from '@/components/drawer-modal-footer';
import { SchemaPatternEnum } from '@/interface';
import SchemeForm from '@/scheme-form';
import PageLoading from '@/components/page-loading';
import { usePageForm } from '@/hooks';
import { useTriggerLogic } from '@/hooks/useLogic';
import { ClickRecord } from '@/components/buttons';
import { getModalPageFormProps, ModalPageFormProps } from './interface';
import { getSubmitFormValues } from '@/utils/formUtils';

import { message } from 'ant-design-vue';

const ModalPageForm = defineComponent({
  name: 'ModalPageForm',
  inheritAttrs: false,
  props: getModalPageFormProps(),
  setup(props: ModalPageFormProps) {
    const submitLoading = ref(false);

    const loadingDone = ref(false);

    const [triggerLogic] = useTriggerLogic(props.getLogicConfig, () => {
      submitLoading.value = false;
    });

    const setSubmitLoading = (nextSubmitLoading: boolean) => {
      submitLoading.value = nextSubmitLoading;
    };

    const pageFormArgsRef = computed(() => {
      const { formConfig, onFormMount, getLogicConfig, events, extraLogicParams, options } = props;

      return {
        formConfig,
        onFormMount,
        options,
        getLogicConfig,
        logicParams: extraLogicParams,
        events,
        autoRefreshForm: false,
      };
    });

    const pageFormRef = usePageForm(pageFormArgsRef);

    const submit = (formValues: any) => {
      const { onConfirm } = props;

      onConfirm?.(formValues);

      submitLoading.value = false;
      handleCloseClick();
    };

    const handleConfirmClick = () => {
      const { form } = pageFormRef.value;

      const { validateFormValues } = props;
      setSubmitLoading(true);
      getSubmitFormValues(form)
        .then((formValues) => {
          if (validateFormValues) {
            validateFormValues(formValues)
              .then(() => {
                submit(formValues);
              })
              .catch((err) => {
                setSubmitLoading(false);
                if (err) {
                  message.warning(err).then(() => void 0);
                }
              });
          } else {
            submit(formValues);
          }
        })
        .catch(() => {
          setSubmitLoading(false);
        });
    };

    const handleCloseClick = (e?: MouseEvent) => {
      const { onClose } = props;

      onClose?.(e);
    };

    const handleAfterClose = () => {
      loadingDone.value = false;
    };

    const handleButtonItemClick = (e, record: ClickRecord) => {
      const { eventCode, clickCodes, code } = record;

      const { events, extraLogicParams, options } = props;

      const { form } = pageFormRef.value;

      if (events?.[eventCode]) {
        return events[eventCode](e, {
          form,
          setSubmitLoading,
          code,
        });
      }

      if (clickCodes.length) {
        setSubmitLoading(true);

        triggerLogic(clickCodes, {
          params: extraLogicParams,
          form,
          effectHook: 'onClick',
          fieldCode: code,
          pageCode: options?.metaSchema?.code,
        });
      }
    };

    const renderFooter = () => {
      const { buttons } = pageFormRef.value;

      const { components, hasConfirmButton, options } = props;

      return (
        <DrawerModalFooter
          buttons={buttons}
          hasConfirmButton={hasConfirmButton ?? options?.pattern !== SchemaPatternEnum.DETAIL}
          onClick={handleButtonItemClick}
          onConfirmClick={handleConfirmClick}
          onCloseCLick={handleCloseClick}
          loading={submitLoading.value}
          disabled={submitLoading.value}
          components={components}
        />
      );
    };

    let timer = null;

    watch(
      () => {
        return {
          formConfig: props.formConfig,
          visible: props.visible,
        };
      },
      () => {
        if (props.visible) {
          const { refreshForm } = pageFormRef.value;
          refreshForm(props.formConfig);
        }
      },
    );

    watch(
      () => props.visible,
      (nextVisible) => {
        setSubmitLoading(false);
        clearTimeout(timer);
        if (nextVisible) {
          timer = setTimeout(() => {
            loadingDone.value = true;
          }, 100);
        }
      },
    );

    return () => {
      const {
        components,
        title,
        width,
        extraLogicParams,
        getLogicConfig,
        events,
        visible,
        language,
      } = props;

      const { schema, form, pattern, formLoading } = pageFormRef.value;

      const loading = formLoading || !visible || !loadingDone.value;

      return (
        <DraggableModal
          title={title || '请填写'}
          maskClosable={false}
          visible={visible}
          confirmLoading={submitLoading.value}
          onOk={handleConfirmClick}
          onCancel={handleCloseClick}
          closable={false}
          width={width || '60%'}
          bodyStyle={{
            overflowY: 'auto',
            maxHeight: 500,
            minHeight: 200,
          }}
          v-slots={{
            footer: renderFooter,
          }}
          destroyOnClose
          afterClose={handleAfterClose}
        >
          <PageLoading loading={submitLoading.value}>
            <SchemeForm
              form={form}
              loading={loading}
              schema={schema}
              components={components}
              pattern={pattern}
              getLogicConfig={getLogicConfig}
              events={events}
              extraLogicParams={extraLogicParams}
              language={language}
            />
          </PageLoading>
        </DraggableModal>
      );
    };
  },
});

export default ModalPageForm;
