// example-vue/src/views/link/LinkCreate.vue
<template>
  <form-page-layout
    :get-logic-config="getLogicConfig"
    :has-group="true"
    :page-code="LinkConfig.CREATE"
    :extra-logic-params="extraLogicParams"
    @back-click="handleBackClick"
  />
</template>

<script setup lang="ts">
import { useRouter } from "vue-router";
import { ref } from "vue";
import getLogicConfig from "@/low-code-meta/logic";
import { FormPageLayout } from "@formlogic/render-vue";
import { apiUrl, LinkConfig } from "./service";

import { validateFormValues, formatFormValues } from "./hooks";

const router = useRouter();

const handleBackClick = () => {
  router.go(-1);
};

const successCallback = () => {
  handleBackClick();
};

const extraLogicParams = ref({
  successCallback,
  action: apiUrl.create,
  extraParams: {},
  validateFormValues,
  formatFormValues,
});
</script>

<style scope></style>

// example/src/pages/link/LinkCreate.tsx
import { FC } from 'react';
import { useNavigate } from 'react-router-dom';
import { FormPageLayout, useJsonMetaSchema } from '@formlogic/render-react';
import getLogicConfig from '@/low-code-meta/logic';

import { LinkConfig, apiUrl } from './service';

import { validateFormValues, formatFormValues } from './hooks';

interface LinkCreateProps {}

const LinkCreate: FC<LinkCreateProps> = () => {
  const navigate = useNavigate();

  const { metaSchema } = useJsonMetaSchema(LinkConfig.CREATE);

  const handleBackClick = () => {
    navigate(-1);
  };

  const successCallback = () => {
    handleBackClick();
  };

  return (
    <FormPageLayout
      hasGroup
      metaSchema={metaSchema}
      getLogicConfig={getLogicConfig}
      extraLogicParams={{
        successCallback,
        action: apiUrl.create,
        extraParams: {},
        validateFormValues,
        formatFormValues,
      }}
      onBackClick={handleBackClick}
    />
  );
};

export default LinkCreate;
