// example-vue/src/views/link/LinkDetail.vue
<template>
  <form-page-layout
    :get-logic-config="getLogicConfig"
    :pattern="SchemaPatternEnum.DETAIL"
    :has-group="true"
    :page-code="LinkConfig.DETAIL"
    :form-config="formConfig"
    :loading="loading"
    @back-click="handleBackClick"
  />
</template>

<script setup lang="ts">
import { useRouter } from "vue-router";
import getLogicConfig from "@/low-code-meta/logic";
import { LinkConfig } from "./service";

import { useLinkDetail } from "./hooks";

import { SchemaPatternEnum, FormPageLayout } from "@formlogic/render-vue";

const router = useRouter();

const [formConfig, loading] = useLinkDetail();

const handleBackClick = () => {
  router.go(-1);
};

const successCallback = () => {
  handleBackClick();
};
</script>

<style scope></style>

// example/src/pages/link/LinkDetail.tsx
import { FC } from 'react';
import { useNavigate } from 'react-router-dom';
import { SchemaPatternEnum, FormPageLayout, useJsonMetaSchema } from '@formlogic/render-react';
import getLogicConfig from '@/low-code-meta/logic';

import { useLinkDetail } from './hooks';

import { LinkConfig } from './service';

interface LinkDetailProps {}

const LinkCreate: FC<LinkDetailProps> = () => {
  const navigate = useNavigate();

  const { metaSchema } = useJsonMetaSchema(LinkConfig.DETAIL);

  const [formConfig, loading] = useLinkDetail();

  const handleBackClick = () => {
    navigate(-1);
  };

  return (
    <FormPageLayout
      hasGroup
      pattern={SchemaPatternEnum.DETAIL}
      loading={loading}
      formConfig={formConfig}
      onBackClick={handleBackClick}
      metaSchema={metaSchema}
      extraLogicParams={{}}
      getLogicConfig={getLogicConfig}
    />
  );
};

export default LinkCreate;
