// packages/component/src/draggable-modal/DraggableModal.tsx
import { Modal, ModalProps } from 'antd';
import { FC } from 'react';
import ModalRender from './ModalRender';

import { useDraggableModalStyle } from '@/draggable-modal/hooks';
import cls from 'classnames';

export interface DraggableModalProps extends ModalProps {
  hasDrag?: boolean;
}

const DraggableModal: FC<DraggableModalProps> = ({
  children,
  className,
  hasDrag,
  ...restProps
}) => {
  const [warpSSR, hashId, prefixCls] = useDraggableModalStyle();

  const modalRender = (modal) => {
    return <ModalRender modal={modal} hasDrag={hasDrag} />;
  };

  return warpSSR(
    <Modal
      {...restProps}
      className={cls(className, hashId, prefixCls)}
      closable={false}
      modalRender={modalRender}
    >
      {children}
    </Modal>,
  );
};

DraggableModal.defaultProps = {
  hasDrag: true,
};

export default DraggableModal;

// packages/render-vue/src/components/draggable-modal/DraggableModal.tsx
import { defineComponent } from 'vue';
import cls from 'classnames';

import { Modal } from 'ant-design-vue';
import { useStylePrefixCls } from '@/components/style/hooks';
import ModalRender from './ModalRender';
import { getDraggableModalProps } from './interface';

const DraggableModal = defineComponent({
  name: 'DraggableModal',
  inheritAttrs: false,
  props: getDraggableModalProps(),
  slots: ['title', 'footer'],
  setup(props, { slots }) {
    const prefixCls = useStylePrefixCls('draggable-modal');

    const modalRender = ({ originVNode }) => {
      return <ModalRender>{originVNode}</ModalRender>;
    };

    return () => {
      const { ...restProps } = props;

      return (
        <Modal
          {...restProps}
          class={cls(prefixCls)}
          closable={false}
          v-slots={{
            ...slots,
            modalRender,
          }}
        >
          {slots.default?.()}
        </Modal>
      );
    };
  },
});

export default DraggableModal;
