// example/src/pages/modal/index.tsx
import { useState } from 'react';
import {
  ModalPageForm,
  FormConfigProps,
  ListLayout,
  TransformsSchemaOptions,
  useJsonMetaSchema,
  useOpen,
  useReloadFlag,
  getJsonMetaSchema,
  SchemaPatternEnum,
} from '@formlogic/render-react';

import getLogicConfig from '@/low-code-meta/logic';

import { apiUrl, ModalConfig, modalRemove, modalDetail } from './service';

import { formatFormValues, validateFormValues, components } from './hooks';

const ModalList = () => {
  const { metaSchema } = useJsonMetaSchema(ModalConfig.LIST);

  const [options, setOptions] = useState<TransformsSchemaOptions>(null);
  const [open, showModal, hiddenModal] = useOpen();

  const [formConfig, setFormConfig] = useState<FormConfigProps>({});

  const [reloadFlag, refreshReloadFlag] = useReloadFlag();

  const [action, setAction] = useState(apiUrl.create);

  const handleAddClick = () => {
    setAction(apiUrl.create);

    showModal();
    getJsonMetaSchema(ModalConfig.CREATE).then((metaSchema) => {
      setOptions({
        metaSchema,
        hasGroup: true,
      });
    });
  };

  const handleRemoveClick = (index, record) => {
    const { code } = record || {};
    modalRemove({ code }).then(() => {
      refreshReloadFlag();
    });
  };

  const handleEditClick = (index, record) => {
    setAction(apiUrl.update);
    showModal();
    getJsonMetaSchema(ModalConfig.EDIT).then((metaSchema) => {
      setOptions({
        metaSchema,
        hasGroup: true,
      });
    });

    const { code } = record || {};
    modalDetail({ code }).then((res) => {
      const { data } = res;
      setFormConfig({
        initialValues: data,
      });
    });
  };

  const handleDetailClick = (index, record) => {
    setAction('');
    showModal();
    getJsonMetaSchema(ModalConfig.DETAIL).then((metaSchema) => {
      setOptions({
        metaSchema,
        hasGroup: true,
        pattern: SchemaPatternEnum.DETAIL,
      });
    });

    const { code } = record || {};
    modalDetail({ code }).then((res) => {
      const { data } = res;
      setFormConfig({
        initialValues: data,
      });
    });
  };

  const successCallback = () => {
    setOptions(null);
    refreshReloadFlag();
    hiddenModal();
  };

  return (
    <>
      <ListLayout
        getLogicConfig={getLogicConfig}
        metaSchema={metaSchema}
        action={apiUrl.page}
        reloadFlag={reloadFlag}
        onEdit={handleEditClick}
        onAdd={handleAddClick}
        onRemove={handleRemoveClick}
        onDetail={handleDetailClick}
      />

      <ModalPageForm
        open={open}
        options={options}
        onClose={hiddenModal}
        getLogicConfig={getLogicConfig}
        formConfig={formConfig}
        extraLogicParams={{
          successCallback,
          action,
          extraParams: {},
          validateFormValues,
          formatFormValues,
        }}
        components={components}
        hasConfirmButton={false}
      />
    </>
  );
};

export default ModalList;

// example-vue/src/views/modal/Modal.vue
<template>
  <list-layout
    :action="apiUrl.page"
    :get-logic-config="getLogicConfig"
    :reload-flag="reloadFlag"
    :page-code="ModalConfig.LIST"
    @add="handleAdd"
    @edit="handleEdit"
    @detail="handleDetail"
    @remove="handleRemove"
  />

  <modal-page-form
    :get-logic-config="getLogicConfig"
    :options="modalPageOptions"
    :visible="modalVisible"
    :has-confirm-button="false"
    :extra-logic-params="logicParams"
    :form-config="formConfig"
    @close="handleModalClose"
  />
</template>

<script setup lang="ts">
import { ref } from "vue";

import {
  ListLayout,
  useReloadFlag,
  useOpen,
  getJsonMetaSchema,
  ModalPageForm,
  SchemaPatternEnum,
} from "@formlogic/render-vue";

import type {
  TransformsSchemaOptions,
  FormConfigProps,
} from "@formlogic/render-vue";

import getLogicConfig from "@/low-code-meta/logic";

import { apiUrl, ModalConfig, modalDetail, modalRemove } from "./service";

import { validateFormValues, formatFormValues } from "./hooks";

const [reloadFlag, refreshReloadFlag] = useReloadFlag();

const [modalVisible, showModal, hiddenModal] = useOpen();

const modalPageOptions = ref<TransformsSchemaOptions | null>(null);

const logicParams = ref({});
const formConfig = ref<FormConfigProps>({});

const handleModalClose = () => {
  hiddenModal();
};

const successCallback = () => {
  modalPageOptions.value = null;
  refreshReloadFlag();
  hiddenModal();
};

const handleAdd = () => {
  showModal();

  formConfig.value = {};

  logicParams.value = {
    successCallback,
    action: apiUrl.create,
    extraParams: {},
    validateFormValues,
    formatFormValues,
  };

  getJsonMetaSchema(ModalConfig.CREATE).then((metaSchema) => {
    modalPageOptions.value = {
      metaSchema,
      hasGroup: true,
    };
  });
};

const getRecordDetail = (record: any) => {
  modalDetail({ code: record.code }).then((res) => {
    const { data } = res;
    formConfig.value = {
      initialValues: data,
    };
  });
};

const handleEdit = (index: number, record: any) => {
  showModal();

  getRecordDetail(record);

  logicParams.value = {
    successCallback,
    action: apiUrl.update,
    extraParams: {},
    validateFormValues,
    formatFormValues,
  };

  getJsonMetaSchema(ModalConfig.EDIT).then((metaSchema) => {
    modalPageOptions.value = {
      metaSchema,
      hasGroup: true,
    };
  });
};

const handleDetail = (index: number, record: any) => {
  showModal();

  getRecordDetail(record);

  getJsonMetaSchema(ModalConfig.DETAIL).then((metaSchema) => {
    modalPageOptions.value = {
      metaSchema,
      hasGroup: true,
      pattern: SchemaPatternEnum.DETAIL,
    };
  });
};

const handleRemove = (index: number, record: any) => {
  const { code } = record || {};
  modalRemove({ code }).then(() => {
    refreshReloadFlag();
  });
};
</script>

<style scope></style>
