// packages/render/src/components/dynamic-schema/index.tsx
import { FC, PropsWithChildren } from 'react';
import { observer, RecursionField, useField } from '@formily/react';
import { useDynamicSchema, useJsonMetaSchema } from '@/hooks';
import { Skeleton } from 'antd';

export interface DynamicSchemaProps extends PropsWithChildren {
  pageCode?: string;
}

const DynamicSchema: FC<DynamicSchemaProps> = observer(({ pageCode, children }) => {
  const field = useField();

  const { metaSchema } = useJsonMetaSchema(pageCode);

  const [schema, done] = useDynamicSchema(metaSchema);

  return (
    <Skeleton loading={!done}>
      <RecursionField basePath={field.address} schema={schema} onlyRenderProperties />
    </Skeleton>
  );
});

export default DynamicSchema;

// packages/render-vue/src/components/dynamic-schema/DynamicSchema.tsx
import { Skeleton } from 'ant-design-vue';
import { defineComponent, toRef } from 'vue';
import { RecursionField, useField,observer } from '@/formily-vue';

import { getDynamicSchemaProps } from './interface';
import { useJsonMetaSchema } from '@/hooks/useJsonMetaSchema';
import { useDynamicSchema } from '@/hooks/useDynamicSchema';

const DynamicSchema = observer(
  defineComponent({
    name: 'DynamicSchema',
    inheritAttrs: false,
    props: getDynamicSchemaProps(),

    setup(props) {
      const pageCodeRef = toRef(props, 'pageCode');

      const field = useField();

      const { metaSchema, loading } = useJsonMetaSchema(pageCodeRef);

      const { schemaRef, doneRef } = useDynamicSchema(metaSchema);

      return () => {
        return (
          <Skeleton loading={loading.value || !doneRef.value}>
            <RecursionField
              basePath={field.value.address}
              schema={schemaRef.value}
              onlyRenderProperties={true}
            />
          </Skeleton>
        );
      };
    },
  }),
);

export default DynamicSchema;
