// packages/render-vue/src/components/buttons/Buttons.tsx
import { CustomButtonMode } from '@/interface';

import { Space } from 'ant-design-vue';
import { defineComponent, h } from 'vue';
import CustomButton from '@/components/custom-button';
import { ButtonsProps, getButtonsProps } from './interface';
import { formatComponentProps } from '@/utils';

const Buttons = defineComponent({
  name: 'Buttons',
  props: getButtonsProps(),
  inheritAttrs: false,
  setup(props: ButtonsProps) {
    return () => {
      const { buttons, components, loading, disabled, onClick } = props;

      return (
        <Space>
          {buttons?.map((item) => {
            const { name, logics, eventCode, code, component, componentProps } = item || {};

            const clickCodes =
              logics
                ?.filter((item) => item.effectHook === 'onClick')
                .map((item) => item.logicCode) || [];

            const Component = components?.[component] || CustomButton;

            return h(Component, {
              type: 'default',
              ...formatComponentProps(componentProps),
              loading,
              disabled,
              key: code,
              title: name,
              onClick: async (e) => {
                await onClick?.(e, {
                  code,
                  eventCode,
                  clickCodes,
                  name,
                });
              },
              mode: CustomButtonMode.text,
            });
          })}
        </Space>
      );
    };
  },
});

export default Buttons;

// packages/render/src/components/buttons/index.tsx
import { CustomButton, CustomButtonMode, CustomButtonProps } from '@formlogic/component';
import { FC, MouseEvent } from 'react';
import { Components, MetaSchemaData } from '@/interface';

import { Space } from 'antd';

export interface ClickRecord extends Pick<MetaSchemaData, 'code' | 'name' | 'eventCode'> {
  clickCodes: string[];
}

export interface ButtonsProps extends Omit<CustomButtonProps, 'onClick'> {
  buttons?: MetaSchemaData[];
  onClick?: (e: MouseEvent<HTMLElement>, record: ClickRecord) => void;
  components?: Components;
}

const Buttons: FC<ButtonsProps> = ({ buttons, loading, components, disabled, onClick }) => {
  return (
    <Space>
      {buttons?.map((item) => {
        const { name, logics, eventCode, code, component, componentProps } = item || {};

        const clickCodes =
          logics?.filter((item) => item.effectHook === 'onClick').map((item) => item.logicCode) ||
          [];

        const Component = components?.[component] || CustomButton;

        return (
          <Component
            type="default"
            {...componentProps}
            loading={loading}
            disabled={disabled}
            key={code}
            onClick={async (e) => {
              await onClick?.(e, {
                code,
                eventCode,
                clickCodes,
                name,
              });
            }}
            mode={CustomButtonMode.text}
          >
            {name}
          </Component>
        );
      })}
    </Space>
  );
};

export default Buttons;
