// example/src/pages/link/index.tsx
import { ListLayout, useJsonMetaSchema, useReloadFlag } from '@formlogic/render-react';
import { useNavigate } from 'react-router-dom';

import getLogicConfig from '@/low-code-meta/logic';
import { getQueryUrl } from '@/utils/utils';
import { apiUrl, LinkConfig, linkRemove } from './service';

const LinkList = () => {
  const navigate = useNavigate();

  const { metaSchema } = useJsonMetaSchema(LinkConfig.LIST);

  const [reloadFlag, refreshReloadFlag] = useReloadFlag();

  const handleAddClick = () => {
    navigate(LinkConfig.CREATE_LINK);
  };

  const handleRemoveClick = (index, record) => {
    const { code } = record || {};
    linkRemove({ code }).then(() => {
      refreshReloadFlag();
    });
  };

  const handleEditClick = (index, record) => {
    const { code } = record || {};
    navigate(getQueryUrl(LinkConfig.EDIT_LINK, { code }));
  };

  const handleDetailClick = (index, record) => {
    const { code } = record || {};
    navigate(getQueryUrl(LinkConfig.DETAIL_LINK, { code }));
  };

  return (
    <ListLayout
      getLogicConfig={getLogicConfig}
      metaSchema={metaSchema}
      action={apiUrl.page}
      reloadFlag={reloadFlag}
      onEdit={handleEditClick}
      onAdd={handleAddClick}
      onRemove={handleRemoveClick}
      onDetail={handleDetailClick}
    />
  );
};

export default LinkList;

// example-vue/src/views/link/Link.vue
<template>
  <list-layout
    :action="apiUrl.page"
    :get-logic-config="getLogicConfig"
    :reload-flag="reloadFlag"
    :page-code="LinkConfig.LIST"
    @add="handleAdd"
    @edit="handleEdit"
    @detail="handleDetail"
    @remove="handleRemove"
  />
</template>

<script setup lang="ts">
import getLogicConfig from "@/low-code-meta/logic";

import { apiUrl, LinkConfig, linkRemove } from "./service";

import { ListLayout, useReloadFlag } from "@formlogic/render-vue";

import { useRouter } from "vue-router";

const [reloadFlag, refreshReloadFlag] = useReloadFlag();

const router = useRouter();

const handleAdd = () => {
  router.push({
    path: LinkConfig.CREATE_LINK,
  });
};

const handleEdit = (index: number, record: any) => {
  const { code } = record || {};

  router.push({
    path: LinkConfig.EDIT_LINK,
    query: {
      code,
    },
  });
};

const handleDetail = (index: number, record: any) => {
  const { code } = record || {};
  router.push({
    path: LinkConfig.DETAIL_LINK,
    query: {
      code,
    },
  });
};

const handleRemove = (index: number, record: any) => {
  const { code } = record || {};
  linkRemove({ code }).then(() => {
    refreshReloadFlag();
  });
};
</script>

<style scope></style>
