// packages/render-vue/src/components/array-pagination/ArrayPagination.tsx
import { defineComponent, ref, watch } from 'vue';
import { Pagination, Space } from 'ant-design-vue';
import cls from 'classnames';
import PaginationStatusSelect from '@/components/pagination-status-select';
import { STYLE_PREFIX } from '@/utils/constant';
import {
  ArrayPaginationProps,
  getArrayPaginationProps,
} from '@/components/array-pagination/interface';

const prefixCls = `${STYLE_PREFIX}-array-pagination`;

const ArrayPagination = defineComponent({
  props: getArrayPaginationProps(),
  setup(props: ArrayPaginationProps, { slots }) {
    const current = ref(1);
    const pageSize = props.pageSize || 10;

    const handleChange = (nextCurrent: number) => {
      current.value = nextCurrent;
      props.onChange?.(current.value, pageSize);
    };

    watch(
      () => props.dataSource,
      (nextDataSource) => {
        const total = nextDataSource?.length || 0;
        const totalPage = Math.ceil(total / pageSize);

        if (totalPage > 0 && totalPage < current.value) {
          handleChange(totalPage);
        }
      },
    );

    return () => {
      const {
        pageSize: propsPageSize,
        size: propsSize,
        dataSource: propsDataSource,
        onChange,
        ...restProps
      } = props;

      const size = props.size || 'small';
      const dataSource = props.dataSource || [];
      const startIndex = (current.value - 1) * pageSize;
      const endIndex = startIndex + pageSize - 1;
      const total = dataSource?.length || 0;
      const totalPage = Math.ceil(total / pageSize);

      const pages = Array.from(new Array(totalPage)).map((_, index) => {
        const page = index + 1;
        return {
          label: page,
          value: page,
        };
      });

      const renderPagination = () => {
        if (totalPage <= 1) return;
        return (
          <div class={cls(`${prefixCls}`)}>
            <Space>
              <PaginationStatusSelect
                value={current.value}
                pageSize={pageSize}
                onChange={handleChange}
                options={pages}
              />
              <Pagination
                {...restProps}
                pageSize={pageSize}
                current={current.value}
                total={dataSource.length}
                size={size}
                showSizeChanger={false}
                onChange={handleChange}
                hideOnSinglePage
              />
            </Space>
          </div>
        );
      };

      return slots.default(dataSource?.slice(startIndex, endIndex + 1), renderPagination(), {
        startIndex,
        endIndex,
      });
    };
  },
});

export default ArrayPagination;

// packages/render/src/components/array-pagination/index.tsx
import { FC, ReactElement, ReactNode, useEffect, useState } from 'react';

import { Pagination, PaginationProps, Space } from 'antd';
import StatusSelect from '@/components/pagination-status-select';
import cls from 'classnames';
import { PaginationContext, useArrayPaginationStyle } from './hooks';
import { observer } from '@formily/react';

interface ArrayPaginationProps extends PaginationProps {
  dataSource?: any[];
  children?: (
    dataSource: any[],
    pagination: ReactNode,
    options: {
      startIndex: number;
      endIndex: number;
    },
  ) => ReactElement;
}

const ArrayTablePagination: FC<ArrayPaginationProps> = observer(
  ({
    pageSize: propsPageSize,
    size: propsSize,
    dataSource: propsDataSource,
    children,
    ...restProps
  }) => {
    const [current, setCurrent] = useState(1);

    const [wrapSSR, hashId, prefixCls] = useArrayPaginationStyle();
    const pageSize = propsPageSize || 10;
    const size = propsSize || 'default';
    const dataSource = propsDataSource || [];
    const startIndex = (current - 1) * pageSize;
    const endIndex = startIndex + pageSize - 1;
    const total = dataSource?.length || 0;
    const totalPage = Math.ceil(total / pageSize);

    const pages = Array.from(new Array(totalPage)).map((_, index) => {
      const page = index + 1;
      return {
        label: page,
        value: page,
      };
    });

    const handleChange = (current: number) => {
      setCurrent(current);
    };

    useEffect(() => {
      if (totalPage > 0 && totalPage < current) {
        handleChange(totalPage);
      }
    }, [totalPage, current]);

    const renderPagination = () => {
      if (totalPage <= 1) return;
      return (
        <div className={cls(`${prefixCls}`, hashId)}>
          <Space>
            <StatusSelect
              value={current}
              pageSize={pageSize}
              onChange={handleChange}
              options={pages}
              notFoundContent={false}
            />
            <Pagination
              {...restProps}
              pageSize={pageSize}
              current={current}
              total={dataSource.length}
              size={size}
              showSizeChanger={false}
              onChange={handleChange}
              hideOnSinglePage
            />
          </Space>
        </div>
      );
    };

    return wrapSSR(
      <>
        <PaginationContext.Provider value={{ totalPage, pageSize, changePage: handleChange }}>
          {children?.(dataSource?.slice(startIndex, endIndex + 1), renderPagination(), {
            startIndex,
            endIndex,
          })}
        </PaginationContext.Provider>
      </>,
    );
  }
);

export default ArrayTablePagination;
