// packages/component/src/input/index.tsx
import React, { FC } from 'react';
import { Input as AntdInput, InputProps as AntdInputProps } from 'antd';

export interface InputProps extends AntdInputProps {}

const Input: FC<InputProps> = ({ readOnly, value, ...restProps }) => {
  return readOnly ? <span>{value}</span> : <AntdInput value={value} {...restProps} />;
};

export default Input;

// packages/render-vue/src/components/input/index.tsx
import { defineComponent } from 'vue';
import inputProps from 'ant-design-vue/es/input/inputProps';
import { Input as AntdInput } from 'ant-design-vue';
import { observer } from '@/formily-vue';

const Input = observer(
  defineComponent({
    name: 'Input',
    inheritAttrs: false,
    props: inputProps(),
    setup(props, { attrs }) {
      return () => {
        const { readOnly } = attrs;
        return readOnly ? <span>{props.value}</span> : <AntdInput {...props} />;
      };
    },
  }),
);

export default Input;
