// packages/render-react/src/components/drawer-modal-footer/index.tsx
import { CloseButton, CustomButton, LeftRightSlot } from '@formlogic/component';

import Buttons, { ButtonsProps } from '@/components/buttons';

import { CheckOutlined } from '@ant-design/icons';
import { FC, MouseEvent } from 'react';

export interface DrawerModalFooterProps extends ButtonsProps {
  hasFooter?: boolean;
  hasCloseButton?: boolean;
  hasConfirmButton?: boolean;
  hasButtons?: boolean;
  onConfirmClick: (e: MouseEvent<HTMLButtonElement>) => void;
  onCloseCLick: (e: MouseEvent<HTMLButtonElement>) => void;
}

const DrawerModalFooter: FC<DrawerModalFooterProps> = ({
  buttons,
  onClick,
  loading,
  disabled,
  onConfirmClick,
  onCloseCLick,
  hasCloseButton,
  hasConfirmButton,
  hasFooter,
  hasButtons,
  components,
}) => {
  if (!hasFooter) {
    return null;
  }

  const left = hasCloseButton ? <CloseButton loading={loading} onClick={onCloseCLick} /> : null;

  return (
    <LeftRightSlot
      left={left}
      right={
        <>
          {hasButtons ? (
            <Buttons
              loading={loading}
              disabled={disabled}
              buttons={buttons}
              onClick={onClick}
              components={components}
            />
          ) : null}

          {hasConfirmButton ? (
            <CustomButton
              loading={loading}
              disabled={disabled}
              onClick={onConfirmClick}
              type="primary"
              icon={<CheckOutlined />}
              key="confirmBtn"
            >
              确定
            </CustomButton>
          ) : null}
        </>
      }
    />
  );
};

DrawerModalFooter.defaultProps = {
  hasFooter: true,
  hasButtons: true,
  hasCloseButton: true,
  hasConfirmButton: true,
};

export default DrawerModalFooter;

// packages/render-vue/src/components/drawer-modal-footer/DrawerModalFooter.tsx
import { defineComponent, VNode } from 'vue';
import LeftRightSlot from '@/components/left-right-slot';
import CustomButton from '@/components/custom-button';
import Buttons, { CloseButton } from '@/components/buttons';
import { CheckOutlined } from '@ant-design/icons-vue';
import { DrawerModalFooterProps, getDrawerModalFooterProps } from './interface';

const DrawerModalFooter = defineComponent({
  name: 'DrawerModalFooter',
  props: getDrawerModalFooterProps(),
  setup: (props: DrawerModalFooterProps) => {
    return () => {
      const {
        hasCloseButton,
        onCloseCLick,
        buttons,
        onClick,
        disabled,
        loading,
        components,
        hasConfirmButton,
        hasButtons,
        onConfirmClick,
      } = props;

      const slots: Record<string, () => VNode> = {};

      if (hasCloseButton) {
        slots.left = () => {
          return <CloseButton onClick={onCloseCLick} />;
        };
      }

      if (hasConfirmButton || hasButtons) {
        slots.right = () => {
          return (
            <>
              {hasButtons ? (
                <Buttons
                  loading={loading}
                  disabled={disabled}
                  buttons={buttons}
                  onClick={onClick}
                  components={components}
                />
              ) : null}

              {hasConfirmButton ? (
                <CustomButton
                  title="确定"
                  onClick={onConfirmClick}
                  loading={loading}
                  disabled={disabled}
                  type="primary"
                  v-slots={{
                    icon: () => <CheckOutlined />,
                  }}
                />
              ) : null}
            </>
          );
        };
      }

      return <LeftRightSlot v-slots={slots} />;
    };
  },
});

export default DrawerModalFooter;
