// packages/render-vue/src/components/buttons/BackButton.tsx
import { RollbackOutlined } from '@ant-design/icons-vue';

import CustomButton, { CustomButtonProps } from '../custom-button';
import { defineComponent } from 'vue';

export interface BackButtonProps extends Omit<CustomButtonProps, 'icon'> {}

const BackButton = defineComponent({
  name: 'BackButton',
  setup(props: BackButtonProps) {
    const handleBackClick = (e) => {
      const { onClick } = props;
      if (onClick) {
        onClick(e);
        return;
      }
      history.back();
    };

    return () => {
      return (
        <CustomButton
          title="返回"
          {...props}
          onClick={handleBackClick}
          v-slots={{
            icon: () => <RollbackOutlined />,
          }}
        />
      );
    };
  },
});

export default BackButton;

// packages/component/src/buttons/back-button/index.tsx
import { RollbackOutlined } from '@ant-design/icons';
import { FC, forwardRef } from 'react';
import CustomButton, { CustomButtonProps } from '@/buttons/custom-button';

export interface BackButtonProps extends Omit<CustomButtonProps, 'icon'> {}

const BackButton: FC<BackButtonProps> = forwardRef(({ children, onClick, ...restProps }, ref) => {
  const handleBackClick = (e) => {
    if (onClick) {
      onClick(e);
      return;
    }
    history.back();
  };

  return (
    <CustomButton
      title="返回"
      {...restProps}
      onClick={handleBackClick}
      icon={<RollbackOutlined />}
      ref={ref}
    >
      {children}
    </CustomButton>
  );
});

export default BackButton;
