// packages/render-vue3/src/renderer-layout/scheme-table-form/SchemeTableForm.tsx
import {
  clone,
  formatComponentProps,
  FormProvider,
  setValidateLanguage,
} from '@formlogic/render-core-vue3';
import { ElEmpty , ElSkeleton  } from 'element-plus';
import { merge, omit } from 'lodash-es';
import {
  computed,
  defineComponent,
  nextTick,
  onMounted,
  ref,
  toRef,
  watch,
  watchEffect,
} from 'vue';

import { useNotifyDevtools } from '@/hooks';
import useDOMRect from '@/hooks/dom/useDOMRect';
import useCreateSchemaField from '@/hooks/useSchemaField';
import { LIST_FILED_CODE } from '@/utils/constant';

import { getSchemeTableFormProps, SchemeTableFormProps } from './interface';

const SchemeTableForm = defineComponent({
  name: 'SchemeTableForm',
  inheritAttrs: false,
  props: getSchemeTableFormProps(),
  setup(props: SchemeTableFormProps, { listeners }) {
    const { components } = props;

    const dataSourceRef = toRef(props, 'dataSource');
    const formRef = toRef(props, 'form');
    const defaultSelectedRowsRef = toRef(props, 'selectedRows');

    const SchemaField = useCreateSchemaField();

    const [contentRect, domRef] = useDOMRect<HTMLDivElement>();

    useNotifyDevtools(toRef(props, 'form'));

    const selectedRows = ref<any[]>([]);

    const setSelectedRows = (nextSelectedRows: any[]) => {
      selectedRows.value = nextSelectedRows;
    };

    watchEffect(() => {
      setValidateLanguage(props.language ?? 'zh-CN');
    });

    const scrollY = ref(450);

    watchEffect(() => {
      if (contentRect.value) {
        const { height } = contentRect.value;

        scrollY.value = height - 140;
      }
    });

    const agGridOptions = computed(() => {
      return merge({});
    });

    watch(
      () => {
        const form = formRef.value;
        const dataSource = dataSourceRef.value;
        const { hasClearSelectedRows } = props;

        return {
          form,
          dataSource,
          hasClearSelectedRows,
        };
      },
      ({ form, dataSource, hasClearSelectedRows }) => {},
      {
        immediate: true,
      },
    );

    watchEffect(() => {
      const defaultSelectedRows = defaultSelectedRowsRef.value;
      setSelectedRows(defaultSelectedRows || []);
    });

    const inject = () => {
      const form = formRef.value;
      form.query(LIST_FILED_CODE).take((target) => {
        target.inject({
          selectedRows: () => {
            return selectedRows.value;
          },
          setSelectedRows: () => {
            return setSelectedRows;
          },
        });
      });
    };

    const setComponentProps = () => {
      const form = formRef.value;

      const {
        hasPagination,
        pageSize,
        currentPage,
        total,
        tableLoading,
        title,
        hasMasterDetail,
        rowKey,
        childRowKey,
        ...restProps
      } = props;

      const formatProps = formatComponentProps({
        on: listeners,
        props: restProps,
      });

      form.query(LIST_FILED_CODE).take((target) => {
        const componentProps: Record<string, any> = {
          ...formatProps,
          loading: tableLoading,
          pagination: {
            pageSize: Number(pageSize ?? 30),
            current: Number(currentPage ?? 1),
            total: Number(total ?? 0),
          },
        };

        nextTick(() => {
          target.setComponentProps(
            omit(componentProps, [
              'schema',
              'language',
              'hasClearSelectedRows',
              'form',
              'dataSource',
              'selectedRows',
            ]),
          );
        });
      });
    };

    onMounted(() => {
      setComponentProps();
      inject();
    });

    watch(
      () => {
        return {
          ...omit(props, 'dataSource'),
          agGridOptions: agGridOptions.value,
        };
      },
      () => {
        setComponentProps();
      },
      { immediate: true },
    );

    return () => {
      const { schema, form, loading } = props;
      const formId = form?.id || 'formId';

      return (
        <ElSkeleton
          style={{
            height: '100%',
          }}
          loading={loading}
          animated
          throttle={500}
        >
          <FormProvider key={formId} form={form}>
            <div
              class={`form-id-${form?.id}`}
              style={{
                height: '100%',
              }}
              ref={domRef}
            >
              {schema ? (
                <SchemaField schema={clone(schema)} components={components} />
              ) : (
                <ElEmpty description="暂无数据" />
              )}
            </div>
          </FormProvider>
        </ElSkeleton>
      );
    };
  },
});

export default SchemeTableForm;

// packages/render/src/scheme-table-form/index.tsx
import { FC, Key, useEffect, useMemo, memo, useState } from 'react';
import { Form, setValidateLanguage } from '@formily/core';
import { FormProvider } from '@formily/react';

import { Empty, Skeleton } from 'antd';

import useCreateSchemaField from '@/hooks/useSchemaField';

import { ISchema } from '@formily/react';
import { toArray } from '@/utils';
import { LIST_FILED_CODE } from '@/utils/constant';
import { ListTableProps } from '@/components/list-table';

import { useDeepEffect, useDOMRect } from '@formlogic/component';
import { RowSelectionType } from 'antd/es/table/interface';
import { Components } from '@/interface';

export interface SchemeTableFormProps
  extends Omit<
    ListTableProps,
    'selectedRowKeys' | 'setSelectedRowKeys' | 'selectedRows' | 'setSelectedRows' | 'onTableChange'
  > {
  schema: ISchema;
  form: Form;
  dataSource: any[];
  currentPage: number;
  total: number;
  pageSize: number;
  language?: string;
  loading?: boolean;
  rowKey?: string;
  hasRowSelection?: boolean;
  hasClearSelectedRows?: boolean;
  selectedRows?: any[];
  rowSelectionType?: RowSelectionType;
  components?: Components;
}

const SchemeTableForm: FC<SchemeTableFormProps> = ({
  schema,
  loading,
  language,
  components,
  dataSource,
  form,
  selectedRows: defaultSelectedRows,
  rowKey,
  hasRowSelection,
  rowSelection,
  onChange,
  currentPage,
  total,
  pageSize,
  rowSelectionType,
  hasClearSelectedRows,
  ...restProps
}) => {
  const [selectedRowKeys, setSelectedRowKeys] = useState<Key[]>([]);

  const [selectedRows, setSelectedRows] = useState<any[]>([]);

  const SchemaField = useCreateSchemaField();

  const [scrollY, setScrollY] = useState(450);

  const [contentRect, domRef] = useDOMRect<HTMLDivElement>();

  const tableRowKey = useMemo(() => {
    return rowKey || 'id';
  }, [rowKey]);

  useEffect(() => {
    if (contentRect) {
      const { height } = contentRect;
      setScrollY(height - 140);
    }
  }, [contentRect]);

  useEffect(() => {
    setValidateLanguage(language ?? 'zh-CN');
  }, [language]);

  useEffect(() => {
    if (form.id) {
      form.setValuesIn(LIST_FILED_CODE, dataSource);

      if (hasClearSelectedRows) {
        setSelectedRows([]);
        setSelectedRowKeys([]);
      }
    }
  }, [form?.id, dataSource, hasClearSelectedRows]);

  useEffect(() => {
    setSelectedRowKeys(defaultSelectedRows?.map((item: any) => item[tableRowKey]) || []);
    setSelectedRows(defaultSelectedRows || []);
  }, [defaultSelectedRows, tableRowKey]);

  const handleRowSelectionChange = (rowKeys: Key[], changeSelectedRows: any[], info) => {
    if (rowSelectionType === 'radio') {
      setSelectedRows(changeSelectedRows);
      setSelectedRowKeys(rowKeys);

      rowSelection?.onChange?.(rowKeys, changeSelectedRows, info);
    } else {
      const allDataSourceKey =
        toArray(dataSource).map((item: any, index) => item[tableRowKey] || index) || [];

      // 更新旧值选中的数据
      const selectedRowsMap = toArray(defaultSelectedRows).map((item: any) => {
        const record = changeSelectedRows.find(
          (current) => current[tableRowKey] === item[tableRowKey],
        );
        if (record) {
          return record;
        }
        return item;
      });

      const nextSelectedRows = selectedRowsMap
        .filter((item: any) => !allDataSourceKey.includes(item[tableRowKey]))
        .concat(changeSelectedRows.filter((item) => allDataSourceKey.includes(item[tableRowKey])));

      const nextSelectedRowKeys = nextSelectedRows.map((item: any) => item[tableRowKey]);

      setSelectedRows(nextSelectedRows);

      setSelectedRowKeys(nextSelectedRowKeys);

      rowSelection?.onChange?.(nextSelectedRowKeys, nextSelectedRows, info);
    }
  };

  const getRowSelectionConfig = () => {
    if (hasRowSelection) {
      return {
        ...rowSelection,
        selectedRowKeys,
        selectedRows,
        type: rowSelectionType ?? 'checkbox',
        onChange: handleRowSelectionChange,
      };
    }
    return null;
  };

  const nextRowSelection = getRowSelectionConfig();

  useDeepEffect(() => {
    if (form) {
      form.query(LIST_FILED_CODE).take((target) => {
        target.setComponentProps({
          ...restProps,
          rowKey: tableRowKey,
          rowSelection: nextRowSelection,
          onTableChange: onChange,
          selectedRowKeys,
          setSelectedRowKeys,
          selectedRows,
          setSelectedRows,
          scrollY,
          pagination: {
            current: Number(currentPage),
            total,
            pageSize: Number(pageSize),
          },
        });
      });
    }
  }, [
    form?.id,
    currentPage,
    total,
    pageSize,
    onChange,
    tableRowKey,
    restProps,
    nextRowSelection,
    scrollY,
    selectedRowKeys,
    selectedRows,
  ]);

  return (
    <Skeleton loading={!!loading}>
      <FormProvider form={form}>
        <div
          className={`form-id-${form?.id}`}
          style={{
            height: '100%',
          }}
          ref={domRef}
        >
          {schema ? (
            <SchemaField schema={schema} components={components} />
          ) : (
            <Empty description="暂无数据" />
          )}
        </div>
      </FormProvider>
    </Skeleton>
  );
};

SchemeTableForm.defaultProps = {
  loading: false,
  rowKey: 'id',
};

export default memo(SchemeTableForm);
