// packages/render-vue/src/components/buttons/CloseButton.tsx
import { CloseOutlined, RollbackOutlined } from "@ant-design/icons-vue";

import CustomButton, { CustomButtonProps } from '../custom-button';
import { defineComponent } from 'vue';

export interface BackButtonProps extends Omit<CustomButtonProps, 'icon'> {}

const CloseButton = defineComponent({
  name: 'CloseButton',
  setup(props: BackButtonProps) {

    return () => {
      return (
        <CustomButton
          title="关闭"
          {...props}
          v-slots={{
            icon: () => <CloseOutlined />,
          }}
        />
      );
    };
  },
});

export default CloseButton;

// packages/component/src/buttons/close-button/index.tsx
import { CloseOutlined } from '@ant-design/icons';
import { FC, forwardRef } from 'react';
import CustomButton, { CustomButtonProps } from '@/buttons/custom-button';


export interface CloseButtonProps extends Omit<CustomButtonProps, 'icon'> {}

const CloseButton: FC<CloseButtonProps> = forwardRef(
  ({ children, ...restProps }, ref) => {
    return (
      <CustomButton title="关闭" {...restProps} icon={<CloseOutlined />} ref={ref}>
        {children}
      </CustomButton>
    );
  },
);

export default CloseButton;
