// packages/render-react/src/components/array-table/index.tsx
import { FC } from 'react';

import { observer, useField } from '@formily/react';

import { ArrayField } from '@formily/core';
import ArrayTableBase, { ArrayTableBaseProps } from '@/components/array-table-base';

export interface ArrayTableProps extends ArrayTableBaseProps {}

const ArrayTable: FC<ArrayTableProps> = observer((props) => {
  const field = useField<ArrayField>();

  const handleRemove = (index) => {
    field.remove(index).then(() => void 0);
  };

  const handleAdd = () => {
    field.push({}).then(() => void 0);
  };

  return <ArrayTableBase {...props} onRemove={handleRemove} onAdd={handleAdd} />;
});

export default ArrayTable;

// packages/render-vue/src/components/array-table/ArrayTable.tsx
import { observer } from '@/utils/observer';
import { defineComponent } from 'vue';
import { ArrayTableBase } from '@/components/array-table-base';
import { ArrayField } from '@formily/core';
import { useField } from '@/formily-vue';

const ArrayTable = observer(
  defineComponent({
    name: 'ArrayTable',
    props: [],
    setup(props) {
      const field = useField<ArrayField>();

      const handleRemove = (index) => {
        field.value.remove(index).then(() => void 0);
      };

      const handleAdd = () => {
        field.value.push({}).then(() => void 0);
      };

      return () => {
        return <ArrayTableBase {...props} onRemove={handleRemove} onAdd={handleAdd} />;
      };
    },
  }),
);

export default ArrayTable;
