// packages/render/src/components/form-grid/index.tsx
import React, {
  useLayoutEffect,
  useRef,
  useMemo,
  PropsWithChildren,
  FC,
  CSSProperties,
} from 'react';
import { markRaw } from '@formily/reactive';
import { observer } from '@formily/react';
import { Grid } from '@formily/grid';

import { useFormLayoutContext } from '@/components/form-layout/hooks';
import cn from 'classnames';
import { FormGridContext, FormGridValueContext, useFormGridStyle } from './hooks';

export interface FormGridProps extends FormGridValueContext, PropsWithChildren {
  className?: string;
  style?: CSSProperties;
}

const FormGrid: FC<FormGridProps> = observer(({ className, style, children, ...props }) => {
  const layout = useFormLayoutContext();
  const options = {
    columnGap: layout?.gridColumnGap ?? 8,
    rowGap: layout?.gridRowGap ?? 4,
    ...props,
  };

  const [wrapSSR, hashId, prefixCls] = useFormGridStyle();

  const grid = useMemo(() => markRaw(new Grid(options)), [Grid.id(options)]);

  const ref = useRef<HTMLDivElement>();

  useLayoutEffect(() => {
    return grid.connect(ref.current);
  }, [grid]);

  return wrapSSR(
    <FormGridContext.Provider value={grid}>
      <div
        className={cn(`${prefixCls}-layout`, hashId, className)}
        style={{
          ...style,
          gridTemplateColumns: grid.templateColumns,
          gap: grid.gap,
        }}
        ref={ref}
      >
        {children}
      </div>
    </FormGridContext.Provider>,
  );
});

export default FormGrid;

// packages/render-vue/src/components/form-grid/FormGrid.tsx
import { markRaw } from '@formily/reactive';

import { Grid } from '@formily/grid';

import { useFormLayoutContext } from '@/components/form-layout/hooks';

import { defineComponent, ref, onMounted, computed } from 'vue';

import { FormGridProps, formGridProps } from '@/components/form-grid/interface';
import { observer } from '@/formily-vue';

const FormGrid = observer(
  defineComponent({
    name: 'FormGrid',
    inheritAttrs: false,
    props: formGridProps,
    setup(props: FormGridProps, { slots }) {
      const layout = useFormLayoutContext();

      const gridInstance = computed(() => {
        const options = {
          columnGap: layout?.gridColumnGap ?? 8,
          rowGap: layout?.gridRowGap ?? 4,
          ...props,
        };
        return markRaw(new Grid(options));
      });

      const domRef = ref<HTMLDivElement>();

      onMounted(() => {
        gridInstance.value.connect(domRef.value);
      });

      return () => {
        return (
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: gridInstance.value.templateColumns,
              gap: gridInstance.value.gap,
            }}
            ref={domRef}
          >
            {slots?.default()}
          </div>
        );
      };
    },
  }),
);

export default FormGrid;
