// packages/render-vue/src/components/feedback-badge/FeedbackBadge.tsx
import { defineComponent } from 'vue';
import { useField } from '@/formily-vue';
import { Badge } from 'ant-design-vue';
import { FeedbackBadgeProps, getFeedbackBadgeProps } from '@/components/feedback-badge/interface';

const FeedbackBadge = defineComponent({
  name: 'FeedbackBadge',
  props: getFeedbackBadgeProps(),
  setup(props: FeedbackBadgeProps, { slots }) {
    const field = useField();

    return () => {
      const { name } = props;

      const errors = field.value.form.queryFeedbacks({
        type: 'error',
        address: `${name ? field.value.address.concat(name) : field.value.address}.*`,
      });

      if (errors.length) {
        return (
          <Badge size="small" class="errors-badge" count={errors.length}>
            {slots.default()}
          </Badge>
        );
      }

      return slots.default();
    };
  },
});

export default FeedbackBadge;

// packages/render/src/components/feedback-badge/index.tsx
import { observer, useField,SchemaKey } from '@formily/react';
import { Badge } from 'antd';
import React, { FC, PropsWithChildren } from 'react';


interface FeedbackBadgeProps extends PropsWithChildren {
  name?: SchemaKey;
}

const FeedbackBadge: FC<FeedbackBadgeProps> = observer(({ name, children }) => {
  const field = useField();

  const errors = field.form.queryFeedbacks({
    type: 'error',
    address: `${name ? field.address.concat(name) : field.address}`,
  });

  if (errors.length) {
    return (
      <Badge size="small" className="errors-badge" count={errors.length}>
        {children}
      </Badge>
    );
  }

  return <>{children}</>;
});

export default FeedbackBadge;
